index.js

To prevent this from happening. Please merge ASAP:

Fix RNIapModule.refreshPurchaseItems

---

android/src/main/java/com/reactlibrary/RNIapModule.java

Fixed callback when the user cancel the purchase

Fix cancel callback

---

android/src/main/java/com/reactlibrary/RNIapModule.java

Added signature to buyItem response

---

index.d.ts
index.js

- Separated platform specified types
- Added JSDoc decorators
- Modified some android specified methods to return null if the Platform is not matched
WIP - Some JSDoc is incomplete because I do not fully understand its behaviors, need help to make a meaningful description.

WIP: Improve typings, with JSDoc

---

README.md
package.json

Release 0.2.14

---

README.md

Example was buyItem, it should be buySubscribeItem.

Changed the readme for ## Subscription section.

---

ios/RNIapIos.m

As inserting nil into NSDictionary is not allowed

Default itemType & currencyCode to empty string

---

ios/RNIapIos.m

Reverts dooboolab/react-native-iap#74

Revert "Default itemType & currencyCode to empty string"

---

README.md

This pull request updates the README with a couple of required steps for ejected apps.

Update README with ejected apps notes

---

android/src/main/java/com/dooboolab/RNIap/RNIapModule.java

fix missing char in RNIapModule.java which causing build/run error on android

Hotfix/0.3.2.1 - fix missing char in RNIapModule.java

---

README.md
android/src/main/java/com/dooboolab/RNIap/RNIapModule.java
issue_template.md
package.json

Resolved conflict from `master` and `dev` branch. Please commit to `dev` branch!

Published 0.3.7

---

README.md
package.json

Another resolved.

---

README.md
index.js
package.json

Resolved conflict from `dev` and `master` pr.

Stable module `0.3.9`.

---

README.md
android/src/main/java/com/dooboolab/RNIap/RNIapModule.java
index.d.ts
index.js
package.json

Implemented endConnection for billing client on android.

Published 0.3.10

---

README.md
android/src/main/java/com/dooboolab/RNIap/RNIapModule.java
index.d.ts
index.js
package.json

Implemented refreshItems for android to consume all items to rebuy.

Published to npm 0.3.13.

---

ios/RNIapIos.m

Knowing error code helps to resolve the problem. 
NOTE: Error code from iOS can be negative value.

Pass error code when unexpected error occurs.

---

index.d.ts

keeps types in sync with the changes in #32

type updates

---

ios/RNIapIos.m

When I tested with Airplane mode, getProduct never resolved/rejected the promise. Fix this by handling the delegate properly.

Handle network error

---

android/build.gradle

The lastest package gave the following error when compiled:
```
* Where:
Build file '/Users/mshen/Projects/native/maestro/node_modules/react-native-iap/android/build.gradle' line: 29
* What went wrong:
A problem occurred evaluating project ':react-native-iap'.
> Cannot invoke method versionCode() on null object
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

add version code

---

README.md
index.js
package.json

Haven't removed in `index.d.ts` as to not cause a conflict, whichever of this and #235 you merge first, I will update the other one to fix that 👌

Drop support for React Native <0.54

---

index.js

Add initConnection to default export object

---

ios/RNIapIos.h
ios/RNIapIos.m

Fix Issue 230.
https://github.com/dooboolab/react-native-iap/issues/230

Merge fetch products

---

ios/RNIapIos.m

Omitted allocating array. This will fix the issue. Sorry.

Add allocating array

---

README.md
index.js
ios/RNIapIos.m

Add clear product function, comments.

Clearproducts

---

ios/RNIapIos.m

Fixes https://github.com/dooboolab/react-native-iap/issues/290

Use NSError's localizedDescription instead of custom error messages

---

index.js

Same issue (and fix) that #280 but for `buyProductWithoutFinishTransaction`

dummy value

---

android/src/main/java/com/dooboolab/RNIap/RNIapModule.java

Catch if mService is null and reject the promise #310

Additional Catch

---

README.md
index.d.ts
ios/RNIapIos.m

Reverts dooboolab/react-native-iap#344

Revert "Expose BCP47 language tag for iOS."

---

README.md
package.json

Edit `readme`.
Co-authored-by: @13ArturBruno

Fix typos, add links

---

.travis.yml
package-lock.json
package.json

Add travis

---

.travis.yml
README.md
RNIapExample/package-lock.json
RNIapExample/package.json

Travis Config

---

index.js.flow

Hello,
thank you for the great package!
We've been using custom Flow definitions for the last ~3 months and I think they are now stable and reliable enough to be added to the codebase.

Start adding Flow type definitions

---

index.d.ts
index.js.flow

Issue : https://github.com/dooboolab/react-native-iap/issues/440

Fix flow and typescript transactionDate type

---

index.d.ts
index.js.flow

See corresponding issue : https://github.com/dooboolab/react-native-iap/issues/448

Fix subscription period and unit typing

---

ios/RNIapIos.m

`introductoryPriceNumberOfPeriodsIOS` shows always 1 for free trial even if the trial duration was 3 days or 2 weeks

Fetch correct number of periods from introductory price

---

ios/RNIap.xcodeproj/project.pbxproj

fixes #499
Add tvOS target for appletvs

add tvos as build target

---

IapExample/App.js
android/src/main/java/com/dooboolab/RNIap/RNIapModule.java
index.js
package.json

Released 3.0.0-rc.16
* Fixes #530

Fixes #530 enhanced

---

CHANGELOG.md
IapExample/App.js
IapExample/android/app/BUCK
IapExample/android/app/build.gradle
IapExample/android/app/src/main/AndroidManifest.xml
IapExample/android/app/src/main/java/com/dooboolab/iapexample/MainActivity.java
IapExample/android/app/src/main/java/com/dooboolab/iapexample/MainApplication.java
README.md
android/src/main/java/com/dooboolab/RNIap/RNIapModule.java
index.d.ts
index.js
index.js.flow
package.json

Implement acknowledgePurchaseAndroid

---

CHANGELOG.md
IapExample/App.js
README.md
index.d.ts
index.js.flow
package.json

- Fixed typo for PurchaseProduct.
- Update example code.
- Update `flow` and `ts` types.

Release 3.2.2

---

IapExample/App.js
README.md

Update acknowledgePurchaseAndroid() example

---

CHANGELOG.md
ios/RNIapIos.m
package.json

+ Fixes `ios` build for target under `12.2`.

Fixes #577

---

.travis.yml
CHANGELOG.md
index.js
package.json
tsconfig.json
yarn.lock

Release 3.3.1

---

index.d.ts
index.js.flow
package.json

- Improved typing for updates in `3.3.0` mostly in #589 
- Fixes #597

[3.3.2] Added missing types on updates in 3.3.0

---

index.js

Should fix #603, not sure how to test.

Add finishTransactionIOS to the default export

---

CHANGELOG.md
package.json

Release 3.3.9

---

RNIap.podspec

fix source_files path and tag version format
maybe related with #627, but I'm not sure

chore: fix podspec

---

index.d.ts

Add more types to PurchaseError

---

index.d.ts

Add more types to acknowledgePurchaseAndroid response

---

README.md

As stated here: https://github.com/dooboolab/react-native-iap/issues/679#issuecomment-527155320

Update readme to include a section about cancelling subscriptions

---

README.md

Typo, `openUrl` should be `openURL`

Rename openUrl to openURL

---

index.d.ts

fix: interface "ID" extending a primitive type

---

index.ts

Fixes https://github.com/dooboolab/react-native-iap/issues/744

Return correct Subscription[] type for getSubscriptions

---

README.md

Add example backend link

---

android/src/main/java/com/dooboolab/RNIap/RNIapModule.java
package.json

Release 4.0.3

---

CHANGELOG.md
README.md
package.json

Release 4.0.4

---

index.ts

Fixed type for finishTransaction.

finishTransaction. Fixed type isConsumable from string to boolean.

---

CHANGELOG.md
IapExample/App.js
README.md
index.ts
package.json

- Resolve #797.
- Resolve #831

Enhanced `finishTransaction` method to be more useful

---

type/apple.d.ts

Fix https://github.com/dooboolab/react-native-iap/issues/845

Fix type for pending_renewal_info

---

RNIap.podspec

This PR adds support for tvos in podspec file.

Add tvos platform in podspec

---

android/src/main/java/com/dooboolab/RNIap/RNIapModule.java
index.ts
package.json

* Update `requestionSubscription` code on android side
- The flow of the code were not clean and correct.
* Support ProrationModesAndroid enum type for handling better proration mode
Fixes #888

[Release] 4.4.0

---

index.ts

See
- https://github.com/dooboolab/react-native-iap/blob/master/index.ts#L152
- https://github.com/dooboolab/react-native-iap/blob/master/index.ts#L158
- https://github.com/dooboolab/react-native-iap/blob/master/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java#L144
The [documentation in the readme is correct](https://github.com/dooboolab/react-native-iap#methods) though.

Promise returns a boolean

---

ios/RNIapIos.m

Wrap every access to validProducts in an @synchronized-Block. This might impact the performance but it fixes the crashes described in Issue #849 for me.
Closes #849

Hopefully Fix Issue #849

---

CHANGELOG.md
IapExample/ios/IapExample/AppDelegate.m
IapExample/ios/Podfile.lock
README.md
ios/IAPPromotionObserver.m
ios/RNIapIos.m
package.json

Add a guide to add `IAPPromotionObserver` in iOS`

---

index.ts

Add export keyword to ProductPurchase interface
This library helped me a lot! Thanks!!

Export ProductPurchase interface

---

README.md

- Add `finishTransaction` method explanation.

chore(README): Update `Finishing a Purchase`

---

README.md

Hey there!
Thanks big time for the lib and your hard work
Here is a modest contribution on some typo I found on the readme ;)

fix: Remove some typo in readme

---

CHANGELOG.md
IapExample/package.json
IapExample/yarn.lock
README.md
android/src/main/java/com/dooboolab/RNIap/RNIapModule.java
package.json

* packageNameAndroid
* obfuscatedAccountIdAndroid
* obfuscatedProfileIdAndroid

Expose more android variables on requests

---

README_AMAZON.md
android/gradle/wrapper/gradle-wrapper.properties
android/src/main/java/com/dooboolab/RNIap/RNIapAmazonListener.java

Fixes https://github.com/dooboolab/react-native-iap/issues/1190

Fixed Amazon products prices parsing

---

ios/RNIapIos.h
ios/RNIapIos.m

Added a promise to the clearTransaction function, to wait until it finishes clearing open transactions
https://github.com/dooboolab/react-native-iap/issues/1120

Patch clear transaction

---

ios/RNIapIos.m

fix(presentCodeRedemptionSheet): Xcode 11 compatibility

---

index.ts

Improving types for iOS subscription based on current `RNIapIos.m` file

Improving typescript types for iOS subscription

---

ios/RNIapIos.m

fix tvos presentCodeRedemptionSheet not available

---

ios/RNIapIos.m

This should prevent #1203 from happening.

Prevent nil countryCode

---

ios/RNIap.xcodeproj/project.pbxproj

- remove IAPPromotionObserver from xcode project
- it is for installing by manual

Fix: remove IAPPromotionObserver

---

ios/RNIapIos.m
package.json
src/iap.ts
yarn.lock

add force refresh receipt for ios to fix this kind of problems
An empty in_app array indicates that StoreKit has not recorded any transactions for that user yet. It may be that the application receipt has not yet been updated. When this happens, your app can inform the user that the receipt does not appear current and ask whether to refresh it
pls take a reference from 
https://stackoverflow.com/questions/36010595/itunes-reciept-validation-in-app-empty#:~:text=3-,An%20empty%20in_app%20array%20indicates%20that%20StoreKit%20has%20not%20recorded,ask%20whether%20to%20refresh%20it.
and 
https://developer.apple.com/library/archive/technotes/tn2413/_index.html#//apple_ref/doc/uid/DTS40016228-CH1-RECEIPT-MY_APP_VALIDATES_ITS_RECEIPT_WITH_THE_APP_STORE_VIA_PAYMENTQUEUE_UPDATEDTRANSACTIONS__AFTER_A_ …

add force refresh receipt for ios 

---

.github/workflows/ci.yml
.github/workflows/publish-package.yml
CHANGELOG.md
README.md
package.json

Enhance github workflow

---

README.md
android/build.gradle
package.json

Attempt on fixing android build
* Hotfix - Revive `jcenter()` removed in #1323

Release 6.0.5

---

android/build.gradle
android/gradle/wrapper/gradle-wrapper.properties
android/src/main/java/com/dooboolab/RNIap/DoobooUtils.java
android/src/main/java/com/dooboolab/RNIap/RNIapAmazonListener.java
android/src/main/java/com/dooboolab/RNIap/RNIapModule.java

fix lint issues [Android]

---

README.md

Fixed manual installation Android markdown layout

---

android/src/play/java/com/dooboolab/RNIap/RNIapModule.java
docs/docs/api_reference/methods.md
src/iap.ts

Credit goes to @Paduado and @hyochan 
See discussion here: https://github.com/dooboolab/react-native-iap/issues/888
It adds documentation so now we can close: 
https://github.com/dooboolab/react-native-iap/issues/555

Adds documentation to Android deferred proration

---

CHANGELOG.md
android/src/play/java/com/dooboolab/RNIap/RNIapModule.java
package.json

Resolve #1409 as done in #1411.
However, we might want the better fixes next time.

Hotfix on getting skus on android

---

android/src/play/java/com/dooboolab/RNIap/RNIapModule.java

Currently `SubscriptionUpdateParams` are not connected to `BillingFlowParams`.

Fix Android subscription update

---

android/src/amazon/java/com/dooboolab/RNIap/RNIapAmazonModule.java

Fixes https://github.com/dooboolab/react-native-iap/issues/1424

moved init code to initConnection method

---

android/src/amazon/java/com/dooboolab/RNIap/RNIapAmazonModule.java

Fixes https://github.com/dooboolab/react-native-iap/issues/1424

Remove init on main thread as it is no longer needed in this version of the SDK

---

src/iap.ts

Fix for issue #1448 
OldSkuAndroid was removed when calling requestPurchase

Fix crash on android requestPurchase

---

.monolinterrc
IapExample/android/build.gradle
IapExample/package.json
IapExample/yarn.lock
docs/docs/installing.md
docs/package.json
package.json
yarn.lock

The project had many discrepant dependency versions. Added validation step to CI and fixed the ones detected

Added monolinter and fixed inconsistent dependency versions

---

src/hooks/useIAP.ts

fix possible typo "requesSubscription" in hooks

fix possible typo "requesSubscription" in hooks

---

ios/RNIapIos.m
ios/RNIapIos.swift

Implements fix proposed here: https://github.com/dooboolab/react-native-iap/issues/1555

fix paramenter name

---

android/src/main/java/com/dooboolab/RNIap/DoobooUtils.kt
ios/RNIapIos.swift

[FIX] Promise never resolved or rejected

---

android/src/amazon/java/com/dooboolab/RNIap/RNIapAmazonModule.kt
android/src/play/java/com/dooboolab/RNIap/RNIapModule.kt

as requested by @mifi in https://github.com/dooboolab/react-native-iap/issues/1496

fix issue #1496 - NativeEventEmitter warnings

---

ios/RNIapIos.m

Fixes https://github.com/dooboolab/react-native-iap/issues/1660

fix: apply handlers to method

---

ios/RNIapIos.swift

Also forget to commit that one in the last PR

fix: clearProducts not resolving on iOS

---

ios/RNIapIos.swift

fix: buyProductWithOffer is not recognized error

---

android/src/amazon/java/com/dooboolab/RNIap/RNIapAmazonModule.kt
android/src/play/java/com/dooboolab/RNIap/RNIapModule.kt

https://github.com/dooboolab/react-native-iap/issues/1659
tested on gradle 6.2

Compile error on Android #1659

---

ios/RNIapIos.swift

Reverts f4161e8 because it breaks iOS

---

android/build.gradle
android/src/play/java/com/dooboolab/RNIap/PlayUtils.kt
android/src/play/java/com/dooboolab/RNIap/RNIapModule.kt
android/src/play/java/com/dooboolab/RNIap/RNIapPackage.kt
android/src/testPlay/java/com/dooboolab/RNIap/RNIapModuleTest.kt

- Refactored ensure connection to reconnect
- ktlint 4.10.0
- added import
- Unit tests for initConnection
- Reverts local change

android unit tests

---

android/src/play/java/com/dooboolab/RNIap/RNIapModule.kt

Fixing #1733 
Please review carefully. It has been quite a while since I developed Android project 👀

fixed reconnection after losing the connection with the billingClient

---

android/build.gradle
android/src/play/java/com/dooboolab/RNIap/RNIapModule.kt
android/src/testPlay/java/com/dooboolab/RNIap/RNIapModuleTest.kt

Refactored the checks for successful billing code so it's not duplicated

Simplify duplicated code for response code validation

---

android/src/amazon/java/com/dooboolab/RNIap/RNIapAmazonModule.kt
android/src/play/java/com/dooboolab/RNIap/RNIapModule.kt

Amazon's documentation recommends fetching the products `onResume`

Refresh Amazon products onResume as per documentation

---

ios/RNIapIos.swift

promotedProduct always resolve null

Fixed function promotedProduct

---

IapExample/.gitignore
IapExample/ios/Podfile
IapExample/ios/Podfile.lock
IapExample/package.json
IapExample/react-native.config.js
IapExample/yarn.lock

Having the Example use local ios files allows us to use IapExample to validate any ios changes

Uses local ios files in Example app

---

src/iap.ts
src/types/index.ts

Fixes https://github.com/dooboolab/react-native-iap/issues/1697. Only including subscriptions/iap products in the result array

Filtering subscriptions and iap products

---

.github/workflows/ci-android.yml
android/build.gradle
android/src/amazon/java/com/dooboolab/RNIap/RNIapAmazonListener.kt
android/src/play/java/com/dooboolab/RNIap/RNIapModule.kt
android/src/play/java/com/dooboolab/RNIap/RNIapModuleInterface.kt
android/src/play/java/com/dooboolab/RNIap/RNIapModuleV4.kt
android/src/play/java/com/dooboolab/RNIap/RNIapPackage.kt
android/src/testPlay/java/com/dooboolab/RNIap/RNIapModuleTest.kt
android/src/testPlay/java/com/dooboolab/RNIap/RNIapModuleTestV4.kt
docs/docs/google_play_billing_5.md
src/iap.ts
src/types/index.ts

This is the first step to migrate to the new Google Play SDK 5.0.0.

update google play to 5

---

.github/workflows/deploy-documentation.yml
docs/yarn.lock

Should fix this cache issue https://github.com/dooboolab/react-native-iap/runs/7640826190?check_suite_focus=true

docs: update yarn.lock for docs using new yarn

---

src/iap.ts

https://github.com/dooboolab/react-native-iap/issues/1808

fix: missing method

---

IapExample/src/screens/Products.tsx
IapExample/src/screens/Subscriptions.tsx
src/types/index.ts

- selectedOfferIndex is part of the new play billing v5, just removing it here to avoid confusion

fix: removed optional parameters from examples

---

src/types/index.ts

fix: changed type of pricingPhaseList to list

---

docs/docs/faq.md

Fixes: https://github.com/dooboolab/react-native-iap/issues/1831

doc: Removed manual native step for promoted products

---

android/src/amazon/java/com/dooboolab/RNIap/RNIapAmazonModule.kt
android/src/play/java/com/dooboolab/RNIap/RNIapModule.kt

Implements feature request from: https://github.com/dooboolab/react-native-iap/issues/1884

@ReactModule annotation

---

IapExample/src/App.tsx
IapExample/src/screens/Products.tsx
ios/RNIapIos.swift
ios/RNIapIosSk2.m
ios/RNIapIosSk2.swift
src/eventEmitter.ts
src/iap.ts

- Brought back old class, renamed new one
- add switch between versions
- format

backwards compatibility2

---

ios/RNIapIos.swift

Removed unnecessary conversion to NSNumber

simplify int to string

---

IapExample/src/App.tsx
IapExample/src/components/State.tsx
IapExample/src/screens/Products.tsx
IapExample/src/screens/Subscriptions.tsx
src/iap.ts

Default to Sk2 if avaiable. This will only make a difference if using ios >=15

Use Sk2 if avaiable

---

.prettierignore
docs/docs/api/.nojekyll
docs/docs/api/README.md
docs/docs/api/classes/PurchaseError.md
docs/docs/api/enums/ErrorCode.md
docs/docs/api/enums/InstallSourceAndroid.md
docs/docs/api/enums/ProductType.md
docs/docs/api/enums/ProrationModesAndroid.md
docs/docs/api/enums/PurchaseStateAndroid.md
docs/docs/api/interfaces/Discount.md
docs/docs/api/interfaces/Product.md
docs/docs/api/interfaces/ProductCommon.md
docs/docs/api/interfaces/ProductPurchase.md
docs/docs/api/interfaces/PurchaseResult.md
docs/docs/api/interfaces/SubscriptionAndroid.md
docs/docs/api/interfaces/SubscriptionIOS.md
docs/docs/api/interfaces/SubscriptionOffer.md
docs/docs/api/interfaces/SubscriptionPurchase.md
docs/docs/api/modules.md
package.json
yarn.lock

Automatically generate documentation

Generate API documentation from code using typedoc

---

docs/docs/api/classes/PurchaseError.md
docs/docs/api/enums/ErrorCode.md
docs/docs/api/enums/InstallSourceAndroid.md
docs/docs/api/enums/ProductType.md
docs/docs/api/enums/ProrationModesAndroid.md
docs/docs/api/enums/PurchaseStateAndroid.md
docs/docs/api/interfaces/Discount.md
docs/docs/api/interfaces/Product.md
docs/docs/api/interfaces/ProductCommon.md
docs/docs/api/interfaces/ProductPurchase.md
docs/docs/api/interfaces/PurchaseResult.md
docs/docs/api/interfaces/SubscriptionAndroid.md
docs/docs/api/interfaces/SubscriptionIOS.md
docs/docs/api/interfaces/SubscriptionOffer.md
docs/docs/api/interfaces/SubscriptionPurchase.md
docs/docs/api/modules.md
docs/docusaurus.config.js

Ignore "broken links" as they are expected

ignore known broken links

---

.github/workflows/deploy-documentation.yml
.gitignore
docs/docs/migrate_to_10.x.x.md
docs/docusaurus.config.js

Quick note on migrating to 10.x.x

add doc on migrating to 10.x.x

---

src/iap.ts
src/types/index.ts

Create types for request purchase and subscription

Create requestSubscription and requestProduct types

---

.github/FUNDING.yml
.github/workflows/deploy-documentation.yml
.gitignore
.prettierignore
docs/docs/guides/purchases.md
docs/docs/migrate_to_10.x.x.md
docs/docs/support-us.md
docs/docusaurus.config.js
ios/RNIapIos.swift
package.json
src/iap.ts
src/index.ts
typedoc.json
yarn.lock

Integrating documentation changeto next

Integrate_doc_changes

---

ios/RNIapIos.m
ios/RNIapIos.swift
ios/RNIapIosSk2.swift
src/iap.ts
src/modules/ios.ts
src/modules/iosSk2.ts
src/types/appleSk2.ts

Improved backward compatibility and  removed single purpose buy methods in favor of a single method with optional parameters

removed legacy buy methods

---

README.md

I won't have time in the foreseeable future to contribute to the project, I prefer removing myself for now. I will try to contribute again later on when I have more free time!
Continue the hard work @andresesfm,
Cheers!

docs: remove from maintainer

---

docs/docs/migrate_to_10.0.0.md
src/internal/platform.ts

- fixes possible invalid transformation on android
- lint doc

fix undefined android purchase

---

docs/docs/migrate_to_11.0.0.md
ios/RNIapIos.m
ios/RNIapIos.swift
ios/RNIapIosSk2.m
ios/RNIapIosSk2.swift
src/iap.ts
src/internal/platform.ts
src/modules/ios.ts
src/modules/iosSk2.ts
src/types/apple.ts
src/types/appleSk2.ts
src/types/index.ts

- from main
- fixes withOffer type

disable sk1

---

ios/RNIapIosSk2.swift

- Sk2 availability on older devices fix
- lint

sk2 runtime older devices

---

src/types/appleSk2.ts
src/types/index.ts

Maps subscription data from Sk2 to Sk1 for hybrid mode

Maps period units from Sk2 to sk1

---

ios/IapSerializationUtils.swift
ios/IapUtils.swift
ios/RNIapIos.swift
ios/RNIapIosSk2.swift

Adding checks so that Storekit 2 is only available on tvOS 15 and higher

Sk2 support for tvOS 15 and higher

---

ios/RNIapIosSk2.swift

- Using IapError instead of Sk1 function
- fix message type

fix missing error sk2 tvOS

---

ios/IapTypes.swift
ios/RNIapIos.swift

Removes the use of `DispatchQueue` for `validProducts` which is not needed since the problem was the use of the wrong data structure

using the proper data structure

---

docs/docs/faq.md

https://github.com/dooboolab/react-native-iap/issues/1172#issuecomment-789582501
Added this comment to docs to explain why.

docs: expand update listener FAQ

---

src/types/appleSk2.ts

This was a problem in Hybrid mode IOS

fixing original Transaction ID

---

android/src/amazon/java/com/dooboolab/RNIap/RNIapAmazonListener.kt

- fix available items filtering
- lint

fix amazon available items

---

ios/IapTypes.swift
ios/RNIapIos.swift
src/types/appleSk2.ts
src/types/index.ts

Fixes transaction types to match TS, and homogenizes them to be numbers

fixes transaction date types to be ints on iOS

---

ios/RNIapIosSk2.swift

Adds the option to return all transactions

option to include all transactions in  Userhistory

---

src/iap.ts

Updated getSubscriptions and getProducts to reflect the name of the parameter

Updated documentation

---

ios/RNIapIos.swift

According to the documentation: https://developer.apple.com/documentation/storekit/skproduct/2936884-subscriptionperiod this is the way to check if a product is a subscription

fix setting iOS subscription type for one-time subscriptions

---

ios/RNIapIos.swift
src/iap.ts
src/types/android.ts

Backfill Android legacy price values after the v5 migration

android legacy price compat

---

src/iap.ts

Reverts dooboolab/react-native-iap#2187

Only remove the check for type but keep the sku filter

---

docs/docs/guides/purchases.md

replace twice import of requestSubscription with requestPurchase.

[chore]: update imports from react-native-iap

---

IapExample/android/build.gradle
IapExample/android/gradle.properties
android/build.gradle
android/gradle.properties

Updating dependency versions and exposing `playBillingSdkVersion` so it can be overridden if necessary.

billing, kotlin and plugin updated

---

android/src/amazon/java/com/dooboolab/RNIap/RNIapAmazonModule.kt
docs/docs/faq.md
src/iap.ts
src/modules/amazon.ts
src/modules/android.ts
src/modules/ios.ts

Added a unified method to handle deeplinking users to the native/web interface to manage their subscriptions

deep link method for subscriptions

---

src/iap.ts

docs: Fix docs

---

android/src/play/java/com/dooboolab/rniap/RNIapModule.kt
src/modules/android.ts
src/types/android.ts

- implement check for feature on device
- compiler fixes
- converted to when
- updated ktlint and formated

android is feature available 2

---

ios/RNIapIosSk2.swift

- adding user canceled error code, so we can distinguish in app what error is intention and what is real error

feat: add ios error reason user canceled

---

docs/docs/api-reference/hooks.md

Hi!
While reviewing the documentation, I noticed a couple of minor typos in the `useIAP()` hook usage example. I am submitting this pull request to correct them. Please let me know if there are any additional changes or reviews needed.
Thanks for maintaining such a helpful library!
Best regards,
Eugene

docs: typos

---

IapExample/README.md

Added Steps for installing node_modules and IOS pods in README.md of IapExample.

docs: Improving IapExample Readme.md

---

android/gradle.properties

Upgrade Amazon's SDK to the latest version

feat: Upgrade Amazon's SDK to 3.0.5
