- ios/RNIapIos.m
> Fix ‘EXC_BAD_ACCESS’ on iOS

- android/build.gradle
- android/src/main/AndroidManifest.xml
- Lowering build tools to those commonly found in other RN github modules (Android 23, and Build Tools 23.0.1)
- Gave the Android packageName an appropriate one instead of the default one (which is com.reactlibrary). This was a problem building for myself due to having another package with this default name.
> Updating Default Android Setup

- ios/RNIap.podspec
`homepage` now is a mandatory attribute in cocopods 
```
[!] The `RNIap` pod failed to validate due to 1 error:
- ERROR | attributes: Missing required attribute `homepage`.
```
> ERROR Pod version 1.3.1

- index.js
- ios/RNIapIos.m
getSubscribeItems() and buySubscribeItem() are currently broken on iOS : they always return undefined. This commit fixes it. It also removes an unused method in the iOS native code.
> Add missing return in getSubscribeItems() on iOS

- ios/RNIapIos.m
See https://github.com/invertase/react-native-firebase/issues/491
> Implement requiresMainQueueSetup to prevent warning in RN 0.49+

- ios/RNIap.xcodeproj/project.pbxproj
This pull request updates the HEADER_SEARCH_PATHS Xcode build setting to include the Cocoapods headers path.
> Update Header Search Path to also point to Cocoapods headers

- android/src/main/java/com/dooboolab/RNIap/RNIapModule.java
This pull request fixes an issue where converting the subscription price to a string was truncating the fractional part of the price.
> Fix the price conversion to also show the fractional part

- index.js
I tried to call `RNIap.consumePurchase(token)` in my React-Native App after calling `RNIap.buyProduct(sku)` and getting product information, but it failed.
After reading the source code, I found the function name is defined as `consumePurchase` in `index.d.ts` but `consumeProduct` in `index.js`, what means `consumePurchase` cannot do anything but throw an exception.
So I just change the function name from `consumeProduct` to `consumePurchase` in `index.js` to satisfy the doc and that's it.
> fix the bugs about different function name defined in index.js and index.d.ts.

- RNIap.podspec
error: bundling failed: ambiguous resolution: module `/x/y/z/index.js` tries to require `react-native`, but there are several files providing this module. You can delete or fix them:
* `/x/y/z/ios/Pods/React/package.json`
* `/x/y/z/node_modules/react-native/package.json`
> Remove deprecated React pod dependency

- RNIap.podspec
Took me way too long to get builds to work again. The change of Podspec didn't break by app before I re-installed all node_modules and, cleared all `build` dirs and redid `pod install`.
This project could use a CI that attempts to do a clean build from scratch to catch these early on.
> Builds again, gotta be careful with these settings

- README.md
- android/src/main/java/com/dooboolab/RNIap/RNIapModule.java
- index.d.ts
- index.js
Hello!
Add optional `oldSku` parameter for `buySubscription` on **Android** to support subscription upgrade/downgrade.
Fix #185
> Android subscription upgrade/downgrade

- index.js
This method is missing from the default export currently, meaning you have to import it separately via a barrel brace or face exceptions that it is not a function.
> add endConnection method to default export

- android/src/main/java/com/dooboolab/RNIap/RNIapModule.java
What do you think? 
The downside of this is that it fails the entire retrieval of items in case there is any "bad" transaction exists... 
I also use optString for "orderId" as it is known to be empty for test order before 2018... But perhaps I should just fail that case as well?
https://github.com/dooboolab/react-native-iap/issues/195
> [Do not merge yet] Return an error when it fails to parse JSON

- ios/RNIapIos.m
As reported here
https://github.com/dooboolab/react-native-iap/issues/233
> fix crash iOS<11.2 when introductoryPrice is nil

- apple.d.ts
- index.d.ts
Recently started using the library in a TypeScript project and noticed a few things that could be improved. Thanks for a great library!
Here are some examples of the improvements seen from VS Code:
I haven't had time to type up the response for `validateReceiptAndroid` yet, but hopefully there will be another pull request soon™ 🚀
> TypeScript Improvements

- index.js
Please merge #238 and #235 first and then I'll rebase this one
> Improve validateReceiptIos

- android/src/main/java/com/dooboolab/RNIap/RNIapModule.java
- package.json
Checking if `mService` is null instead of `mServiceConn` before trying to unbind service. `mServiceConn` will always be an object.
> onHostDestroy fix

- index.js
- ios/RNIapIos.m
Calling finishTransaction, which I mentioned, would be no effect when restarting the App or device itself. So, I looked up the document on iOS I found `transactions` property in skpaymentqueue class, and I used it for this implementation.
https://developer.apple.com/documentation/storekit/skpaymentqueue
I named the new method to `clear transaction` which looks fit better.
Check and test the method. Especially the jsDoc return values etc.
> Force finish transaction

- README.md
- android/src/main/java/com/dooboolab/RNIap/RNIapModule.java
- index.js
The diff might be a bit hard to read but it's mostly indentation changes 🙈 
Basically, I've wrapped all calls with a new `ensureConnection` function. This function will detect if the client hasn't been initialized, and in that case initialize it before running the supplied code.
The end users can continue to call `initConnection` and `endConnection` as before, but it's now optional since a connection will be automatically established if it's needed.
> Automatically handle connection initialization

- index.js
Add missing async, await notation. 
이거 안드로이드는 괜찮은 지 함 보셔요..
> Fix for missing async await.

- android/src/main/java/com/dooboolab/RNIap/RNIapModule.java
In this project, if a promise is not rejected it is successful so returning null was a bit confusing on the Android side. Now it is more consistent with ios.
`const result = await RNIap.initConnection();`
Now the result is `true`
> resolve(null) => resolve(true)

- README.md
Hello.
fix typo in README in validateReceiptIos example
Best Regards, Ilya Pavlov
> typo in validateReceiptIos example

- README.md
- RNIapExample/src/components/pages/First.js
- index.d.ts
- index.js
- ios/RNIapIos.h
- ios/RNIapIos.m
- package.json
Make workaround for #307.
Testing if this could be the workaround.
> Add additional event listener to handle success purchase after failure.

- android/src/main/java/com/dooboolab/RNIap/RNIapModule.java
This PR tries to solve issues brought up in #315 , specifically that methods are invoked on `mBillingClient` when it is `null`. See my comment there for a discussion of the problem. Copy-pasted here, the variable `clientReady` is being used to track if the billing client setup has been completed, by setting it to `false` in the onBillingServiceDisconnected() callback. But `mBillingClient` itself is set to `null` immediately when `endConnection()` is called. This is a mismatch. It's possible for `clientReady` to remain set to `true`, even if `mBillingClient` is `null`. In that case, methods will be invoked by the on the null object instance. It seems that something is preventing `onBillingServiceDisconnected()` from being called.
Solution:
- avoid setting `mBillingClient` to `null`. It is …
> Do not null mBillingClient (#315)

- index.d.ts
Removes the duplicate definition of `freeTrialPeriodAndroid` which declared it as an optional string.
fix #375
> Fix: remove TS duplicate definition of 'freeTrialPeriodAndroid'

- index.d.ts
Declares the function's return type as `EmitterSubscription`
fix #376
> Fix: add return type to TS definition of 'addAdditionalSuccessPurchaseListenerIOS'

- android/src/main/java/com/dooboolab/RNIap/RNIapModule.java
It's quick and dirty but it seems to work for #315. I can't think of a scenario where you would ever want the same listener to hit it's onSetupFinished callback twice. If the app shutdown and restarted, and needed to get a new connection, it would have created a new listener. I also didn't see a way to unsubscribe a listener from the BillingClient.
> Fix for BillingClientImpl Crashes - Promise consumed twice

- RNIapExample/src/components/pages/First.js
[GIVEN]
- Location: Iap example app
- Issue: Button labelled `Get available purchases` gets items instead, which is confusing for newbies like myself:(
[THEN]
- Fix button to correctly display available purchases
Not sure what the correct flow for PRs are -- let me know if there are any issues
> fix example to correctly display available purchases

- README.md
- index.js
- ios/RNIapIos.m
This pull request adds support for the additional `SKProductTransactionObserver` delegates that support promoting In-App Purchase products in the App Store. 
This pull request closes #199.
> Add support for iOS In-App Purchase promotions

- android/src/main/java/com/dooboolab/RNIap/RNIapModule.java
This commit fixes https://github.com/dooboolab/react-native-iap/issues/315
Previous pull request https://github.com/dooboolab/react-native-iap/pull/379 fixed the issue just partially.
Here is the stack showing the case when the app crashes:
```
java.lang.RuntimeException: 
at com.facebook.react.bridge.CallbackImpl.invoke (CallbackImpl.java:28)
at com.facebook.react.bridge.PromiseImpl.reject (PromiseImpl.java:68)
at com.facebook.react.bridge.PromiseImpl.reject (PromiseImpl.java:36)
at com.dooboolab.RNIap.RNIapModule.rejectPromiseWithBillingError (RNIapModule.java:458)
at com.dooboolab.RNIap.RNIapModule.access$300 (RNIapModule.java:46)
at com.dooboolab.RNIap.RNIapModule$3.onBillingSetupFinished (RNIapModule.java:132)
at com.android.billingclient.api.BillingClientImpl$BillingServiceConnection …
```
> Fix for double callback consume crash

- README.md
`consumeProduct()` is the android native function name.
The JS api should be `consumePurchase()`.
> doc: fix api naming consumeProduct -> consumePurchase

- README.md
First of all, thank you for this package and for the time you invested in it!
This is related to #307.
This PR tries to make the readme clearer regarding the motivation and use of the `addAdditionalSuccessPurchaseListenerIOS` method. 
The current readme makes it seem like calling `addAdditionalSuccessPurchaseListenerIOS` is optional, but it's not. If I decide not to support the 'store kit flow', my application can end up receiving payment from users but not acknowledging it. 
I think you wanted to have the example as simple as possible so I tried to do so, while still providing example code on how to handle the 'store kit flow'.
Happy to hear feedback about this
> update readme to better explain 'store kit flow'

- CHANGELOG.md
- RNIap.podspec
- package.json
Fixes #404 
- The new version will be released from `stable` channel from now.
> Add stable branch for podspec

- android/src/main/java/com/dooboolab/RNIap/RNIapModule.java
- index.js
These Additional checks will help in pushing code accessing RNIap plugin to SDK that does not have the plugin in it.
I am sure this will help other developers also to push code remotely without any breakage
> Supporting code push

- android/build.gradle
Fixes build errors related to jcenter missing android-specific
dependencies.
> fix: android: move google repo above jcenter

- apple.d.ts
- index.d.ts
- index.js
- index.js.flow
- ios/RNIapIos.m
iOS launched this new feature that allows apps to have offers for renewing users, in order to "win back lapsed subscribers or retaining current subscribers", says the documentation.
So, this PR has two main components:
The `SKProduct` now has a `discounts` property in order to provide the actual subscription available discounts, I add a new method to parse it and convert to an `NSArray<NSDictionary *>` to be converted to JSON.
This new method allows the user to purchase an offered subscription, the Apple documentation says you must generate a signature to determine the eligibility of the user to this offer, you must do it on your server using a pre-generated private key.
> Your server should respond with the signature string and the additional values it used to generate the signature: a …
> Support to iOS subscription offers

- README.md
- ios/RNIapIos.m
[The API](https://github.com/dooboolab/react-native-iap#methods) defines that `initConnection` returns a string in promise. But on Android, it was returning a boolean. This change fixes that.
> iOS: Return bool in canMakePayments

- README.md
Removing `pod 'RNIap', :path => '../node_modules/react-native-iap'` from the Podfile makes the module not available in apps using Pods so it's better to let it be in the Podfile.
> Remove comments about ejected apps in README

- android/build.gradle
This PR updates _Gradle_ version to `3.2.1` and default build tools version to `28.0.3` to avoid warnings in most versions.
⚠️ Needed to be tested.
> Update Gradle 3.2.1 - build tools version 28.0.3

- android/build.gradle
Currently, local configuration of versions is ignored by this library.
[`hasProperty()`](https://docs.gradle.org/current/javadoc/org/gradle/api/Project.html#hasProperty-java.lang.String-) exists on the `Project` object itself; `Project.ext` uses [`has()`](https://docs.gradle.org/current/javadoc/org/gradle/api/plugins/ExtraPropertiesExtension.html#has-java.lang.String-).
You can test by modifying the main app's `build.gradle`.
```gradle
buildscript {
ext {
buildToolsVersion = "28.0.3"
// [...]
```
With this mr, setting `buildToolsVersion` to something older will result in a warning during build. On current master, changes to `buildToolsVersion` have no effect.
> Fix gradle api usage

- ios/RNIapIos.m
Fixes promo code purchase not being restored.
Checks for transaction state being SKPaymentTransactionStatePurchased and finishes the transaction.
https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/StoreKitGuide/Chapters/DeliverProduct.html#//apple_ref/doc/uid/TP40008267-CH5-SW4
> Fix promo code purchase not being restored.

- index.d.ts
The `Subscription` interface in `index.d.ts` does not align with what I am receiving from `getSubscriptions()`.
- All returned values are strings, no numbers or objects.  
- Platform specific values are optional since they are only returned per specific platform
- introductoryPriceSubscriptionPeriodIOS does not currently exist on interface
- introductoryPriceNumberOfPeriodsIOS does not currently exist on interface
```javascript
androidSubscriptionResponse: [
{
introductoryPricePeriodAndroid: "",
introductoryPriceCyclesAndroid: "",
productId: "xxxx",
price: "49.99",
currency: "USD",
type: "subs",
localizedPrice: "$49.99",
freeTrialPeriodAndroid: "P3D",
title: "xxx",
description: "xxx",
introductoryPrice: "",
subscriptionPeriodAndroid: "P1Y"
},
];
```
```javascript
iOSSubscriptionResponse: …
```
> Fix Platform Specific Type Definitions

- IapExample/App.js
- android/src/main/java/com/dooboolab/RNIap/RNIapModule.java
- index.d.ts
- index.js
- index.js.flow
- ios/RNIapIos.m
- ios warning fixed.
- typings added.
Fixes #511
```
purchaseUpdateSubscription = purchaseUpdatedListener((purchase: ProductPurchase) => {
console.log('purchaseUpdatedListener', purchase);
this.setState({ receipt: purchase.transactionReceipt }, () => this.goNext());
});
purchaseErrorSubscription = purchaseErrorListener((error: PurchaseError) => {
console.log('purchaseErrorListener', error);
Alert.alert('purchase error', JSON.stringify(error));
});
```
> Add `purchase-error` events to handle purchase error

- index.d.ts
In README.md, seems to it is not deprecated at `requestSubscription`.
But index.d.ts, `requestSubscription` is marked as @deprecated.
This PR remove deprecated annotation on `requestSubscription` method.
(If this method is deprecated definitedly, please close this PR and tell me alternative method ;-) )
> Remove deprecated annotation on requestSubscription method in index.d.ts

- index.d.ts
There was no  `purchaseErrorListener` defined and `purchaseUpdatedListener` was added twice.
> fixed typo in TypeScript definition file

- README.md
- index.d.ts
- index.js
- ios/RNIapIos.m
We noticed obtaining the App receipt isn’t as straightforward as we thought. 
NSBundle.mainBundle().appStoreReceiptURL returns an NSURL describing the path behind which the receipt can be found, if there is one!
To quote the documentation: (https://developer.apple.com/documentation/foundation/nsbundle/1407276-appstorereceipturl)
For an application purchased from the App Store, call this method on its application bundle locate the receipt. This method makes no guarantee about whether there is a file at the returned URL — **only that if a receipt is present, that is its location.**
In such a case, you have to start a SKReceiptRefreshRequest. This tries to download a receipt and saves it in the known destination if everything succeeds.
Obviously the process must be asynchronous now.
On top …
> Improved handling of receipts

- README.md
`endConnection()` no longer exists on this package, the function is now called `endConnectionAndroid()`. This change updates the name of the method in the docs.
> Updated method name in readme

- android/src/main/java/com/dooboolab/RNIap/RNIapModule.java
If enablePendingPurchases() is not called, trying to buy a Product on the connection will fail.
> Make ensureConnection always provide a valid BillingClient

- README.md
- README_DEPRECATED.md
These two fields should be exchanged, also removed trailing whitespaced.
---
By the way, may i also prettify the README file, improve readability in normal TextEditor?
> Fix typo in README

- android/src/main/java/com/dooboolab/RNIap/RNIapModule.java
I get an error when trying to purchase a product after calling `getSubscriptions(subSkus)` and `getProducts(productSkus)`, like so:
```
const subscriptions = await RNIap.getSubscriptions(subscriptionIds);
const products = await RNIap.getProducts(productIds);
```
This seems to be because both call `RNIapModule.getItemsByType()`, which replaces the internal SKUs cache. The only way to get it to work without making this change is to call the `getProducts()` or `getSubscriptions()` before trying to purchase.
> Keep valid SKUs in memory

- android/src/main/java/com/dooboolab/RNIap/RNIapModule.java
This fixes the case when onHostDetroy is invoked before onBillingSetupFinished, leading to a NPE in the callback (https://github.com/dooboolab/react-native-iap/issues/606)
> Check billingClient before invoking callback

- android/src/main/java/com/dooboolab/RNIap/RNIapModule.java
Lately we have been getting a large number of crashes when no purchases are received when calling `getPurchasesList`. This small change ensures looping only happens if a list of purchases is received
> Avoid looping on a null purchases list

- ios/RNIapIos.m
This PR makes it possible to use this module while building projects in older XCode versions [issue](https://github.com/dooboolab/react-native-iap/issues/577)
With this change I was able to build project with XCode 10.1 and with XCode 10.3
> fix: make it build with older XCode

- index.js
iOS getSubscriptions return subscriptions that only received ids
- - - -
```js
const A = await RNIap.getSubscriptions(['01.month.subscription']);
console.log('A',A);
const B = await RNIap.getSubscriptions(['01.month.subscription','03.month.subscription']);
console.log('B',B);
const C = await RNIap.getSubscriptions(['01.month.subscription','03.month.subscription','12.month.subscription']);
console.log('C',C);
const D = await RNIap.getSubscriptions(['01.month.subscription','03.month.subscription']);
console.log('D',D);
const E = await RNIap.getSubscriptions(['01.month.subscription']);
console.log('E',E);
```
```
A [{..}]
B [{..},{..}]
C [{..},{..},{..}]
D [{..},{..},]
E [{..}]
```
```
A [{..}]
B [{..},{..}]
C [{..},{..},{..}]
D [{..},{..},{..}]
E [{..},{..},{..}]
```
- - - - -
> fix(getSubscriptions) : iOS return subs properly

- README.md
- index.d.ts
- index.js
- ios/RNIapIos.m
We are having several customers complaining about their purchases not to be confirmed even though they are payed. We identify this might happen when something wrong happens between finishing the payment in the appstore and confirming the purchase. That's why we came with this method: it retrieves the pending transactions (those who are payed but not yet finished), so they can be processed and finished once the user receives his products. This can be very useful as a complement to a 'Restore Purchases' button, which can be pressed when the user has issues with his purchases.
> method to retrieve pending transactions

- android/src/main/java/com/dooboolab/RNIap/RNIapModule.java
Missing item.putBoolean for purchase Item causes the key autoRenewingAndroid to be undefined. 
Closes #669
> Fixed missing item.putBoolean for autoRenewingAndroid key

- IapExample/App.js
I believe that listener's `remove()` should be called in `componentWillUnmount()` instead of `componentWillMount()`.
> Destroying listeners in proper React's life cycle method

- index.d.ts
`autoRenewingAndroid` is not available on `iOS`
`originalTransactionDateIOS` and `originalTransactionIdentifierIOS` are not available on `Android`
So the types should not assume they are there
> Make all SubscriptionPurchase property types optional, as they are different per platform

- index.d.ts
I noticed this was missing.
I have not validated yet if the types are correct. But I assume they are based on: https://github.com/dooboolab/react-native-iap/blob/ae9e0b5c1bf951bede7d2d0a72e4400a3bd20f32/ios/RNIapIos.m#L633-L707
> Add discounts array to Subscription type (iOS Only)

- android/src/main/java/com/dooboolab/RNIap/RNIapModule.java
When running on Android emulator `initConnection` will currently be neither resolved, nor rejected, because java counterpart has doesn't always handle promise. This PR makes it always resolve or reject. In my case, on emulator this will get rejected with `Billing service unavailable on device`.
However, I'm not sure, maybe instead of being rejected, the promise should be resolved with `false` (at least for some codes)?
> fix: fix unresolved promise in initConnection

- CHANGELOG.md
- android/src/main/java/com/dooboolab/RNIap/RNIapModule.java
- index.d.ts
- index.js.flow
- package.json
- Add missing `isAcknowledgedAndroid` variable in getAvailableItems.
Closes #709 
Co-authored-by: Johny8811 <jan.hujsa@gmail.com>
> Update package to 3.4.7

- android/src/main/java/com/dooboolab/RNIap/RNIapModule.java
With this PR it's now possible to know why `initConnection` failed on JS side. So you can distinguish network errors from cases when billing is unavailable.
> feat: improve initConnection errors on android

- index.js.flow
These were added as part of https://github.com/dooboolab/react-native-iap/pull/616 but the flow file never got updated
> Add missing fields to PurchaseResult & PurchaseError

- index.ts
Since after fixing #748 isAcknowledgedAndroid is available for both InAppPurchase and SubscriptionPurchase, I have moved the property to the common base interface ProductPurchase
> Typings: Move isAcknowledgedAndroid to ProductPurchase

- .npmignore
- CHANGELOG.md
- index.ts
- package.json
* fix `validateReceiptAndroid`
- Make template literals properly
* Additionally resolve #757
> fix(validateReceiptAndroid): template literals properly

- index.ts
`finishTransaction` on Android calls non-existing native methods. This should fix it.
> fix: call correct methods in finishTransaction Android

- android/src/main/java/com/dooboolab/RNIap/RNIapModule.java
Calling `requestSubscription()` on Android result in the purchase being made but the promise is never called. This is due to an exception being thrown when trying to resolve the promise, specifically `method threw 'com.facebook.react.bridge.objectalreadyconsumedexception' exception` because the WriteableMap is already consumed when `sendEvent` is called. 
By making a copy before calling it, we get a fresh WriteableMap that we can send to our promise without error.
> [Android] Fixed promise never returned from requestSubscription()

- android/src/main/java/com/dooboolab/RNIap/RNIapModule.java
`sendUnconsumedPurchases` only send unconsumed in-app products but not subscriptions. The app i'm working on uses subscriptions and requires to be able to send receipt to the server about unacknowledged subscriptions. This fixes it.
I also saw that a promise is passed as a parameter but isn't subscribed to inside `index.ts`. As is, this promise is useless so I decided to resolve it with true no matter what at the end of the function.
> [Android] added subs to the list of unconsumed purchases

- ios/RNIapIos.m
Hello again,
Just noticed that whenever the user cancel buying a product, or when the product is bought, nothing happens in JS because the resolve/reject methods aren't called properly.
This commit fixes it 😄
> [iOS] Fixed promise acceptation/rejection not propagated to JS

- android/src/main/java/com/dooboolab/RNIap/RNIapModule.java
React Native 0.61 introduces the `.copy()` method to the WritableMap
interface and this is used as of version 4.0.8 of this library. To keep
compatibility with RN 0.60, manually create a copy.
Fixes #834
> Fix Android compile error for React Native v0.60.x due to missing method

- .npmignore
- ios/RNIapIos.m
- tsconfig.json should not be in the released module, this causes errors in some editors (atom-typescript)
- fix Xcode warning (explicit `self->hasListeners`)
- fix `NSInteger` vs. `NSInteger*` - the intended behaviour is probably quantity as NSInteger.
> Fix some warnings and a bug

- README.md
- android/src/main/java/com/dooboolab/RNIap/RNIapModule.java
1. Fix double precision issue when doing calculations with large numbers. In our case, `priceAmountMicros` can be 3290000000, and `priceAmountMicros / 1000000f` will give incorrect value 3289.999755859375 (3290 is expected).
2. Fix inconsistent return type. On documentation and iOS implementation, all properties of Product are String types. Earlier implementation on Android gives Double type.
We also update documentation of `price` and `localizedPrice` to make it clearer.
> Fix double precision issue and inconsistent return type on Android

- README.md
The link that is on README redirects to iTunes installation, I found [this](https://stackoverflow.com/a/51127481/9241832) answer on StackOverflow that references to a WWDC session. Tested and works properly.
> Update iOS cancel subscription URL

- README.md
- New URL: https://apps.apple.com/account/subscriptions redirects to App Store, and only works on iOS 12 or later.
- Old URL: https://buy.itunes.apple.com/WebObjects/MZFinance.woa/wa/manageSubscriptions redirects to iTunes Store.
Apple doesn't mention those details. I tested on my own iOS 10-13 devices. So the old URL should be kept for reference.
The reason @julioxavierr described in #906 that old URL redirects to iTunes installation is, either the user [deleted iTunes Store](https://support.apple.com/en-us/HT208094) (possible since iOS 12), or the iOS [offloaded unused iTunes Store](https://support.apple.com/en-us/HT201656).
> Improve documentation for iOS subscription URL

- README.md
The method mentioned in README is `clearProducts()` but the correct name should be `clearProductsIOS()`.
> Fix clearProductsIOS method name typo

- CHANGELOG.md
- ios/IAPPromotionObserver.m
- package.json
Attempt to fix #934
- Refered to https://stackoverflow.com/questions/34001868/ios-this-in-app-purchase-has-already-been-bought-pop-up.
@meteorra I will land this shortly to `4.4.2`, please try this out.
> Release 4.4.2

- README.md
Hey @hyochan !
First I have to thank you for the awesome work on react-native-iap 👍
I'm maintaining a few open source projects myself and I know the commitement and time it takes.
Secondly, thank you for starring [react-native-iaphub](https://github.com/iaphub/react-native-iaphub) 🙏 
Your module is making IAP easy on the client side and I'm trying on my side with [IAPHUB](https://www.iaphub.com) to take care of the pain validating receipts on the server side...
[react-native-iaphub](https://github.com/iaphub/react-native-iaphub) is just a simple wrapper of your library directly communicating to IAPHUB.
Was thinking it would be cool to add an option using iaphub in the "Receipt validation" section of the README 🙂 
I added the section in this PR if it sounds good to you.
Thank you!
> Add receipt validation option

- index.ts
The OC code returns `productIdentifier` which is a string type.
> Fix return type of getPromotedProductIOS

- ios/RNIapIos.m
This pull request fixes a couple of issues related to discounts (aka introductory and promotional offers):
1. The product price is a string, but the discount price is a number. Fixed by taking the `stringValue` of `discount.price` when adding to the `discount` dictionary. 
2. If `discount.priceLocale` is `nil`, `NSNumberFormatter` defaults to the system locale rather than the App Store locale. Fixed by defaulting to `product.priceLocale` if `discount.priceLocale` is `nil`. If `product.priceLocale` is also `nil`, `NSNumberFormatter` will then default to the system locale.
> Fix discounts issues

- ios/RNIapIos.m
Hey @hyochan,
We fixed an issue causing the `requestSubscription` or `requestPurchase` promise to not resolve on IOS 14 (Issue: #1058)
The issue is due to how react-native-iap is handling the promises, currently a key is generated (using RCTKeyForInstance) which is the pointer of the product identifier.
The problem is the pointer of `transaction.payment.productIdentifier` is actually different in the `updatedTransactions` method on IOS 14 causing the key to identify the promise to be different therefore the promise isn't found.
The solution in the pull request is to use directly the product identifier instead of the pointer value.
> Fix promise not resolving on IOS14

- index.ts
I want to protect myself by restraining the acceptable skus in my application (either with `type ItemSku = 'sku1' | 'sku2' | ...` or `enum ItemSku { sku1 = 'sku1', sku2 = 'sku2', ... }`
However, `getProducts` returns products with `productId` typed as `string`
getProducts now infers the type of `productId` from its input
This is backward compatible as the typing is optionnal and defaults to the current `string`
> feat: Allow specyfing string subtype for product ids

- android/src/main/java/com/dooboolab/RNIap/RNIapModule.java
- index.ts
- ios/RNIapIos.m
Let users know which productId is the error about, on purchaseErrorListener
Always provided for ios. Not provided for android for non product-specific error
> feat: Let user know which productId was the error about

- index.ts
Not sure of the reason why `any` was here at the beginning. Any clue?
> test: Be more specific in purchaseErrorListener param typing

- RNIap.podspec
Latest Xcode 12 fails to build without a module to depend on `React-Core` directly hence this change is necessary for all native modules on iOS. This change requires React Native 0.60.2 or newer. For more details please check: https://github.com/facebook/react-native/issues/29633#issuecomment-694187116
> fix: Xcode 12 compatibility

- android/src/main/java/com/dooboolab/RNIap/RNIapModule.java
Despite meticoulous local testing, it seems like #1085 introduced a crash when calling `flushFailedPurchasesCachedAsPending`, due to `Collections.EMPTY_LIST` returning a non-mutable List
> fix: prevent UnsupportedOperationException crash

- android/build.gradle
I was unable to create Detox tests without these lines of code specifying the Java version in build.gradle. Basically, without the JavaVersion, the Multidex conversion when compiling tests doesn't work well.
> Adding JavaVersion on build.gradle to work with Detox tests

- index.ts
This is a fix to issue 1131:
https://github.com/dooboolab/react-native-iap/issues/1131
The issue happened because of this change on line 420:
https://github.com/dooboolab/react-native-iap/commit/d5785e55e298934bbbb83c972497ae1d9631e359#diff-b21dbc2d57e14bf6f1b5f81c3a3c3ba5
> Fix for 'RNIapModule.buyItemByType got 6 arguments, expected 7'

- android/src/main/java/com/dooboolab/RNIap/RNIapAmazonModule.java
The merge of #1141 caused an issue with the amazon buyItemByType method
> Fix amazon buyItemByType missing parameters

- README.md
- index.ts
- ios/RNIapIos.m
Add introductory price as string without formating and currency
> Add introductory price as string without formating and currency

- README.md
- index.ts
- ios/RNIapIos.m
This adds the App Store country code to iOS
> Add iOS store country code

- ios/RNIapIos.m
Although `getPendingPurchasesIOS()` typescript definition mentioned like below, 
```ts
/**
* Get the pending purchases in IOS.
* @returns {Promise<ProductPurchase[]>}
*/
export const getPendingPurchasesIOS = async (): Promise<ProductPurchase[]> => {
if (Platform.OS === 'ios') {
await checkNativeiOSAvailable();
return RNIapIos.getPendingTransactions();
}
};
```
Objective-C code had possibility to return `undefined` because it passed `nil` for `resolve()`.
(My app received a crash report because of this. 😭 )
> Fix that getPendingPurchasesIOS() may returns undefined.

- README.md
- index.ts
- ios/RNIapIos.m
This method displays a sheet that enables users to redeem subscription offer codes and works only on real-devices.
> feat: added presentCodeRedemptionSheetIOS

- ios/RNIapIos.m
Solution recommended by rusty120 to avoid a possible deadlock in the promise of the clearTransactionsIOS
https://github.com/dooboolab/react-native-iap/issues/1120#issuecomment-754840685
> Fix posible problem clearTransactionsIOS promise

- index.ts
As per [Apple receipt verification best practices](https://developer.apple.com/documentation/appstorereceipts/verifyreceipt): 
> As a best practice, always call the production URL for verifyReceipt first, and proceed to verify with the sandbox URL if you receive a 21007 status code.
In case if `isTest` parameter is `undefined` or defined as `null` (basically means that developer prefers to perform environment agnostic check:
1. Query production verification endpoint
2. In case if 20017 error is returned - query sandbox receipt verification endpoint
For the cases when `isTest` parameter is explicitly defined as `true` or `false` - run the old logic
> Add sandbox agnostic receipt verification

- CHANGELOG.md
- README.md
- package.json
- src/index.ts
React Naitve IAP hook is out. [Follow the medium post](https://medium.com/dooboolab/announcing-react-native-iap-hooks-96c7ffd3f19a) on how to use it.
The sample code is out in [Sponsor page](https://github.com/hyochan/dooboolab.com/blob/master/src/components/pages/Sponsor.tsx) in [dooboolab.com](https://github.com/hyochan/dooboolab.com) repository which sadly is rejected by Apple because of lacking product features. I will work on another example project to support `react-native-iap`.
More description in https://github.com/dooboolab/react-native-iap/issues/1241#issuecomment-798540785.
> Release 6.0.0

- README.md
- android/src/main/java/com/dooboolab/RNIap/RNIapModule.java
We already have the iOS version for this property, I'm sure in the future both should be renamed just for `introductoryPriceAsAmount`.
But to avoid breaking changes I think this works for now, my team is already using this fork in production because we needed this for both platforms.
> Adding introductoryPriceAsAmountAndroid

- README.md
This PR fixes this doc issue:
delegate does not respond to method paymentQueue:shouldAddStorePayment
https://github.com/dooboolab/react-native-iap/issues/1094
> iOS promo requires calling initConnection first

- android/src/main/java/com/dooboolab/RNIap/RNIapAmazonListener.java
- android/src/main/java/com/dooboolab/RNIap/RNIapAmazonModule.java
Without this addition, `buyItemByType` on Amazon immediately returns a resolved promise.
This change rejects or resolves the promise similar to how the Google Play implementation does.
> [Amazon] Add promise handling for Amazon purchases instead of resolving immediately.

- android/src/main/java/com/dooboolab/RNIap/RNIapAmazonModule.java
Amazon SDK complains when registering the Purchase Listener on any thread other than main (UI)
> [Amazon] register listener on main thread

- IapExample/package.json
- IapExample/yarn.lock
- android/src/main/java/com/dooboolab/RNIap/DoobooUtils.java
Aside from the installer, we can detect if the app has been installed on an Amazon device by following the guidelines described here: https://developer.amazon.com/docs/fire-tv/identify-amazon-fire-tv-devices.html
Especially useful when sideloading the app for testing purposes
Cleaner than the suggested fallback logic: 
```
if (__DEV__) {
RNIap.setFallbackInstallSourceAndroid(RNIap.InstallSourceAndroid.AMAZON);
}
...
```
> fire tv detection

- CHANGELOG.md
- android/src/main/java/com/dooboolab/RNIap/RNIapModule.java
- package.json
As described in the issue below, when requested `proration mode` with `deferred`, purchases can be `null`. Handle this case in the event to know that this was successful.
Resolve #888
> Handle deffered proration in purchasedUpdated listner in android

- android/build.gradle
Setting buildToolsVersion is no longer recommended, it'll default to Android Gradle Plugin defaults. It makes DX worse by requiring multiple versions of build tools by various dependencies require various versions.
> [Android] Remove buildToolsVersion

- package.json
The value of `main` property in `package.json` is "index.ts".
I think this is problematic. For example, `Flow` throws a "Cannot resolve module" error.
> Fix a wrong package.json setting

- ios/RNIapIos.m
Related to #1210
If I cancel during purchase interaction, the following error occurs.
```
Possible Unhandled Promise Rejection (id: 0):
Error: The operation couldn’t be completed. (SKErrorDomain error 2.)
promiseMethodWrapper@http://192.168.0.2:8081/index.bundle?platform=ios&dev=true&minify=false:2220:45
http://192.168.0.2:8081/index.bundle?platform=ios&dev=true&minify=false:201046:43
step@http://192.168.0.2:8081/index.bundle?platform=ios&dev=true&minify=false:200702:25
http://192.168.0.2:8081/index.bundle?platform=ios&dev=true&minify=false:200632:20
http://192.168.0.2:8081/index.bundle?platform=ios&dev=true&minify=false:200604:73
tryCallTwo@http://192.168.0.2:8081/index.bundle?platform=ios&dev=true&minify=false:3446:9
doResolve@http://192.168.0.2:8081/index.bundle?platform=ios&dev=true&mi …
```
> Fix an unnecessary error when canceling a purchase

- package.json
It's more common to not include the `git+` prefix when specifying the repository URL: https://docs.npmjs.com/cli/v7/configuring-npm/package-json#repository
This also leads to a clickable link when invoking `yarn upgrade-interactive`.
> Update URL in package.json

- android/src/main/java/com/dooboolab/RNIap/DoobooUtils.java
- android/src/play/java/com/dooboolab/RNIap/PlayUtils.java
Since the code split between stores, I created a separate file to deal with Google Play-specific logic for handling errors. However, this meant that I inadvertently created a separate copy of the hashmap that holds the promises. This could create a disconnect making some promises not resolve. This PR reverts that change by only using DoobooUtils as the host of such Promises store.
> fix promise resolving logic

- android/src/play/java/com/dooboolab/RNIap/RNIapModule.java
Related to #1385
I should have worked together in my previous PR, but it's missing.
Unlike iOS, Android does not throw warning errors, but It'd be better to be excluded for the same reason.
I don't think it's necessary to release a new version right now. It's enough to be included in the next version.
> Remove an unnecessary reject when canceling by user

- IapExample/android/build.gradle
- IapExample/package.json
- IapExample/yarn.lock
- android/build.gradle
- Bump react-native from 0.61.5 to 0.62.3 in /IapExample
- add jcenter back
> dependabot/npm and yarn/IapExample/react native 0.62.3

- babel.config.js
- jest.config.js
- package.json
Recent `tests` are failing after upgrading packages.
Use `transform` from `babel-jest`.
```
transform: {
"^.+\\.(js|jsx|ts|tsx)$": "babel-jest",
}
```
Add `transformIgnorePatterns` like below.
```
transformIgnorePatterns: [
'node_modules/(?!@react-native|react-native)'
],
```
And adding plugins to `babel.config.js` fixed the problem.
```
plugins: [
'@babel/plugin-proposal-class-properties',
'@babel/plugin-proposal-private-methods',
],
```
> Fix recent jest test failing

- android/src/play/java/com/dooboolab/RNIap/RNIapModule.java
When calling initConnection on an Android Emulator fails if not wrapped in catch. 
Resolving to false and returning prevents the crash and is more consistent with usage
> Fix crash when init on Android Emulator

- .vscode/settings.json
- src/iap.ts
I went too far removing code, when not wrapping the `ios:` block with an async block was causing it to evaluate every time regardless of platform. The fix is to add the mentioned wraps that were previously removed
Closes #1454
> Fix android crash by delaying ios check

- CHANGELOG.md
- IapExample/package.json
- IapExample/yarn.lock
- android/src/amazon/java/com/dooboolab/RNIap/RNIapAmazonListener.java
- src/iap.ts
- src/types/index.ts
- yarn.lock
- Added isCanceled to amazon properties
- fix lint
- cleaned up types and refactored common code across platforms
- refactor receipt conversion for Amazon
- verbiage
> improve receipt types

- README.md
- docs/docs/usage_instructions/using_hooks.md
- package.json
- src/hooks/useIAP.ts
- src/hooks/withIAPContext.tsx
- src/index.ts
- tsconfig.json
currently, every time calling `useIAP` hooks, it will call `initConnection` and register listeners with should only be done once when the app starts (as mentioning in the documentation). So I introduce new HOC `withIAPContext`
1. `withIAPContext` HOC responsible for
- Init context
- Init IAP connection
- Register listeners
2. `useIAP` same as before but removing the code that inits IAP and registers listeners.
1. You have to wrap your app with the `withIAPContext` HOC
```jsx
import {withIAPContext} from 'react-native-iap';
const App = () => <View />;
export default withIAPContext(App);
```
2. Later then, somewhere in your components
```jsx
import {withIAP} from 'react-native-iap';
const YourComponent = () => {
const {
connected,
products,
promotedProductsIOS,
subscriptions, …
```
> Use React's Context to manage IAP state

- docs/docs/api_reference/available_purchase.md
- ios/RNIapIos.m
- src/types/index.ts
On iOS, we can `requestPurchaseWithQuantityIOS` which purchase a productId with a specific quantity.
However, in the purchase info when a purchase is completed, we only receive the productId.
I have done some changes so we can now receive both the productId and the requested quantity when a purchase is completed.
The quantity is fetched from the associated payment in the transaction. 
Documentation : https://developer.apple.com/documentation/storekit/skpayment/1506077-quantity?language=objc
> Add quantity in purchase data

- android/build.gradle
It is now set to the last known working version. Note this will still fail CI until there's a new release and IapExample's package version is pointed to that new version
> Setting default AndroidX version

- android/src/play/java/com/dooboolab/RNIap/RNIapModule.java
- ios/RNIapIos.m
If the user does not proceed with the payment, the `RNIap.requestSubscription()` promise never resolves and remains dangling. It's also an issue if you want to show a "payment in progress" spinner while the user is interacting with the system level payment flows, as you don't get informed about the user cancelling, meaning, the spinner spins forever.  
Fixes: https://github.com/dooboolab/react-native-iap/issues/1479
> fix: Cancellled purchase kept promise dangling

- src/types/index.ts
This fixes a type in the ProductCommon interface. 
As long as I have tested in IOS, the ProductCommon does not receive `countryCodeIOS` but `countryCode` and none in Android.
> fix countryCode typing in ProductCommon interface

- docs/docs/usage_instructions/using_hooks.md
Thanks for the repo! It really helped me getting started with IAP 🙂 
There seems to be a slight fix needed in the [hooks document](https://react-native-iap.dooboolab.com/docs/usage_instructions/using_hooks), which might cause confusion to new users.
> fix(docs): Wrong import in hooks documentation

- .npmignore
A `.tsx` file is included in source, which TS loads instead of the JS file, and validates against local TS rules.
Removing this file from the source fixes the issue.
> Update .npmignore to remove TS errors

- android/src/amazon/java/com/dooboolab/RNIap/RNIapAmazonModule.java
- android/src/play/java/com/dooboolab/RNIap/RNIapModule.java
closes #1524. Superseeds other PR as it also includes the change for `RNIapModule.java`
> fix: NativeEventEmitter warnings since ReactNative 0.65

- android/src/amazon/java/com/dooboolab/RNIap/RNIapPackage.kt
- android/src/play/java/com/dooboolab/RNIap/RNIapPackage.kt
RN 0.47 deprecated the method. Remove it entirely.
Some may just remove the `override` to pass the build (`createJSModules overrides nothing` error), but this function is actually can be removed entirely.
see: https://github.com/facebook/react-native/commit/ce6fb337a146e6f261f2afb564aa19363774a7a8
> [8.0] android: remove deprecated method createJSModules in module package

- android/src/play/java/com/dooboolab/RNIap/RNIapModule.java
In the current Android implementation is it possible to get the following error during the invocation of `RNIap.requestPurchase(...)`:
```
{
message: 'Google is indicating that we have some issue connecting to payment.',
debugMessage: 'Invalid SKU details.',
code: 'E_DEVELOPER_ERROR',
responseCode: 5
}
```
It appears that the problem is caused by the changing content of `SkuDetails` (e. g. `skuDetailsToken` in `originalJson`) over time even for the same product. It can happen that after several invocations of `RNIap.getProducts(...)` there will be multiple instances of `SkuDetails` in the `skus` list with the same `sku/productId` and later a wrong instance is chosen to purchase a product during the invocation of `RNIap.requestPurchase(...)`. The proposed implementation should minimize …
> Refresh SkuDetails

- docs/docs/usage_instructions/receipt_validation.md
Make docs clearer with regards to local vs app-store receipt validation.
> chore(docs): update receipt validation docs

- android/src/play/java/com/dooboolab/RNIap/RNIapModule.java
In Billing 4 response from `querySkuDetailsAsync` is returned in background, it causes android app in production to get stuck at this point and it makes impossible further purchases or any other interactions with SKUs. Wrapping `querySkuDetailsAsync` handler in `runOnUiThread` fixes the issue
> fix: android querySkuDetailsAsync ui thread

- .npmignore
Hello,
when installing your package I noticed that its size was over 200 MB. When checking package files, I found out that `.yarn/cache` folder takes those 200 MB. I tried to pack with the updated `.npmignore` and the package size is just 1.0 MB.
You probably accidentally included it in published package, it is ignored in `.gitignore` but not in `.npmignore`.
> ignore yarn cache in npmignore

- .flowconfig
- .github/workflows/ci-android.yml
- .github/workflows/ci-example.yml
- IapExample/android/app/build.gradle
- IapExample/android/build.gradle
- IapExample/package.json
- IapExample/yarn.lock
- android/build.gradle
- docs/docs/installing.md
- src/types/index.ts
- Fixes building issues in relese/8.0.0 branch 
- Fixes flow build by ignoring checks on node_modules
- Removes redundant builds on multiple similar java versions [11,11.0.3]
- Removes unnecessary check of java style
- Removes dependency to the now deprecated to jcenter repo
- Allows for configuration of `kotlinVersion` reading it from the `rootProject` just like the other versions, including default to 1.5.10 (Fixes https://github.com/dooboolab/react-native-iap/issues/1598) 
- Adds missing `introductoryPriceAsAmountAndroid` to typescript (same as https://github.com/dooboolab/react-native-iap/pull/1619)
@hyochan when this is merged into 8.0.0 could you please create a new RC)
> Fixes release/8.0.0 build issues on Android

- ios/RNIapIos.swift
Fixes https://github.com/dooboolab/react-native-iap/issues/1645 by calling resolve once the `SKPaymentQueue` `finishTransaction` has been triggered
Following the history of the file, it looks like this was broken trying to fix https://github.com/dooboolab/react-native-iap/issues/1637 , by adding the promise methods in the header but not calling resolve/reject. I have fixed both methods (finishTransaction and clearTransaction) here credit goes to the people commenting on the issue, it helped a lot to narrow the problem
> Fixes finishTransaction not resolving for iOS

- ios/RNIapIos.swift
Fixed application crash when sending a purchase request and disconnecting the internet immediately after this request
> Crash in the absence of the Internet on the device

- IapExample/App.js
Recoverable errors like interrupted purchases, network failures, failures while processing receipts, etc, are being consumed even though they were recoverable.
Clear transactions calls finishTransaction, which ends updates, and therefore shouldn't be called while there are recoverable transactions awaiting updates.
> Avoid finishing transactions that can still succeed and have not been consumed

- docs/docs/manual_install.md
Fixes documentation as mentioned here https://github.com/dooboolab/react-native-iap/issues/1687
> Fix documentation to use implementation instead of compile (android)

- ios/RNIapIos.swift
Attempt to fix: https://github.com/dooboolab/react-native-iap/issues/1717
Not a swift expert but it seems like this would work. I found that we have to check for possibly nil even if the type is not optional as per https://stackoverflow.com/a/44060466/570612
> swift guard against possible nil value

- android/src/play/java/com/dooboolab/RNIap/RNIapModule.kt
This is my proposed change to attempt a reconnection if the billing client is not initialized. It looks more dramatic than it actually is. The only real change was on `ensureConnection`. All the other changes are formating caused by removing the custom callback `EnsureConnectionCallback` and using lambdas instead since we no longer need to pass the billing Client around as a parameter
> Refactored ensure connection to reconnect

- android/src/play/java/com/dooboolab/RNIap/RNIapModule.kt
- android/src/testPlay/java/com/dooboolab/RNIap/RNIapModuleTest.kt
There is a crash on Android when attempting to test the app using an emulator/device without Play Services. The crash happens before the app initializes. This is because we were creating the billing client in the constructor instead of first checking it Google Play Services was available. This PR fixes it
> First check for billing to be avaiable

- ios/RNIapIos.m
- ios/RNIapIos.swift
- src/iap.ts
According to the issue https://github.com/dooboolab/react-native-iap/issues/1576 there is a need for an extra param for iOS transactions.
> feat(ios-purchase): add appAccountToken to requestPurchase on iOS

- .github/workflows/publish-beta.yml
Manage the `next` release on the separate branch in `next` instead of publishing to the release tag with `npm`.
The downside of previous releases is that the user can't find the stable release of the version and we can't update the latest stable version when there has been a mistake.
Now, when `rebase merge` the `main` branch in `beta`, the CI will run and release the package to with `next` tag instead of the release.
- Related https://github.com/dooboolab/react-native-iap/discussions/1777
> Publish beta on merge in beta branch

- ios/RNIapIos.m
> Fix mismatch between buyProduct signatues in Obj-C and swift

- src/iap.ts
- src/types/index.ts
Conditional union types depending on the props passed. Makes it easier to discover which props are allowed to work together
requestPurchase:
requestSubscription:
> fix: methods types

- src/iap.ts
- src/types/index.ts
This reverts commit 3ac3871.
My changes were crap. We don't care what platform we are passing arguments for, that's internally we determine what to pass to which native methods. So we could pass all android/ios related arguments if we want, doesn't have to be one platform at a time.
> fix: revert "fix: methods types (#1792)"

- src/hooks/withIAPContext.tsx
- src/iap.ts
This attempts to fix issue: https://github.com/dooboolab/react-native-iap/issues/1800
I'm submitting this as a recommendation, I haven't had a chance to test it.
> fix: limit promotedProductListener to iOS

- IapExample/src/App.tsx
- src/types/index.ts
All theses types are being optional on native side and have either default value or being undefined on TS side
Also, question @andresesfm, we have `requestSubscription` to buy a subscription, wouldn't it make more sense to have `requestProduct` for a product, rather than `requestPurchase`? (could be done on another PR, just a curiosity question)
> fix: make all types optional for requestPurchase

- ios/RNIapIos.swift
There seems to be a problem while converting from objective-c to swift.
In a sandbox account with a lot of payment history, the following problems can be easily reproduced.
* `countPendingTransaction` was not assigned ([Reference: 7.5.6 version](https://github.com/dooboolab/react-native-iap/blob/7.5.6/ios/RNIapIos.m#L264))
* `resolve(nil)` is executed unconditionally ([Reference: 7.5.6 version](https://github.com/dooboolab/react-native-iap/blob/7.5.6/ios/RNIapIos.m#L273))
* Not added to observer when calling `initConnection` again after calling `endConnection` ([Reference: 7.5.6 version](https://github.com/dooboolab/react-native-iap/blob/7.5.6/ios/RNIapIos.m#L115))
> [iOS] Fix issues related to pending transactions.

- .github/workflows/publish-package.yml
Bringing up from #1817, remove the example project when releasing the package.
- Closes #1817
Co-authored-by: jeremybarbet <jeremgraph@gmail.com>
> ci: remove example proj on release

- .github/workflows/publish-next.yml
Refer to #1819.
Note that this does not work with cherry-picking since the name of the file is different.
> ci: fix publishing workflow by removing example project

- .eslintrc.js
- package.json
- yarn.lock
Should fix the `Environment key "jest/globals" is unknown` that I'm randomly getting while switching branches or re-generating yarn.lock
> fix: eslint jest

- RNIap.podspec
Originally added here: https://github.com/dooboolab/react-native-iap/pull/869
> fix: bring back TVOS. It was removed in a recent refactoring

- src/index.ts
```ts
import { flushFailedPurchasesCachedAsPendingAndroid } from 'react-native-iap';
```
It wasn't defined anymore and others imports. Related to the refactoring from last week
> fix: export modules through destructured import

- src/iap.ts
Fixes mismatched parameter between Android Native and JS
> passing empty array instead of undefined

- .github/workflows/publish-next.yml
Thanks to @jeremybarbet on resource https://stackoverflow.com/questions/58139406/only-run-job-on-specific-branch-with-github-actions/58142412#58142412.
Try publishing packages dedicated to branches.
> ci: publishing packages dedicated to branches

- IapExample/src/screens/AvailablePurchases.tsx
- IapExample/src/screens/ClassSetup.tsx
- IapExample/src/screens/Products.tsx
- IapExample/src/screens/PurchaseHistories.tsx
- IapExample/src/screens/Subscriptions.tsx
- src/hooks/useIAP.ts
- src/hooks/withIAPContext.tsx
- src/iap.ts
- src/index.ts
- src/purchaseError.ts
- src/types/index.ts
- `IapError` has been renamed to `PurchaseError` and is now extending an Error class. It can be used as follow:
```tsx
try {
requestPurchase(...)
} catch (error) {
if (error instance PurchaseError) {
// error.code, error.message, error.productId, error.debugMessage
}
}
```
> refactor!: create a PurchaseError class

- IapExample/__tests__/App-test.js
- IapExample/src/navigators/StackNavigator.tsx
- IapExample/src/screens/AvailablePurchases.tsx
- IapExample/src/screens/ClassSetup.tsx
- IapExample/src/screens/Products.tsx
- IapExample/src/screens/PurchaseHistory.tsx
- IapExample/src/screens/Subscriptions.tsx
- IapExample/src/screens/index.ts
- docs/docs/usage_instructions/connection_lifecycle.md
- docs/docs/usage_instructions/purchase.md
- src/hooks/useIAP.ts
- src/hooks/withIAPContext.tsx
- src/iap.ts
- src/index.ts
I'm getting a bit lost on my main [PR](https://github.com/dooboolab/react-native-iap/pull/1797), so I will split everything up, should be easier 
- You can't use default export to access method, you need to import it from the object `import RNIap from 'react-native-iap';` -> `import {getProducts} from 'react-native-iap';`
- The hook no longer export `requestPurchase` and `requestSubscription`, they should be import directly from `import { requestPurchase } from 'react-native-iap';`
- `purchaseHistories` and `setPurchaseHistories` has been renamed to `purchaseHistory` and `setPurchaseHistory` to match the original methods
> refactor!: remove support for default export

- IapExample/src/screens/ClassSetup.tsx
- IapExample/src/screens/Products.tsx
- IapExample/src/screens/Subscriptions.tsx
- src/hooks/useIAP.ts
- src/hooks/withIAPContext.tsx
- src/iap.ts
- src/types/index.ts
I flatten the interfaces within the methods to simplify next step of rework. I will start moving (in another PR) all modules specific params as we talked some time ago. It will be as follow:
```ts
requestPurchase({
skus: [''], // common
ios: {
...
},
android: {
..
}
})
```
- All the exposed methods are now taking an object of parameters, rather than named params. e.g. `requestSubscription('com.example.sub', false)` -> `requestSubscription({ sku: 'com.example.sub', andDangerouslyFinishTransactionAutomaticallyIOS: false })`
- `requestPurchase` now takes an array of `Sku` -> `requestPurchase({ skus: ['com.example.sub'] })`. For iOS, only one Sku can be defined, for Android, it can be multiple
- Remove the `InAppPurchase` type, which was already defined as `ProductPurchase`
> refactor!: make all methods take an object of params

- IapExample/__tests__/App-test.js
- IapExample/src/navigators/StackNavigator.tsx
- IapExample/src/screens/AvailablePurchases.tsx
- IapExample/src/screens/ClassSetup.tsx
- IapExample/src/screens/Products.tsx
- IapExample/src/screens/PurchaseHistory.tsx
- IapExample/src/screens/Subscriptions.tsx
- IapExample/src/screens/index.ts
- docs/docs/usage_instructions/connection_lifecycle.md
- docs/docs/usage_instructions/purchase.md
- src/eventEmitter.ts
- src/hooks/useIAP.ts
- src/hooks/withIAPContext.tsx
- src/iap.ts
- src/index.ts
- src/internal/enhancedFetch.ts
- src/internal/fillProductsWithAdditionalData.ts
- src/internal/index.ts
- src/internal/platform.ts
- src/purchaseError.ts
- src/types/index.ts
- ci: replace publication for next branch
- refactor!: create a PurchaseError class (#1866)
- refactor!: remove support for default export (#1864)
- chore: clean up non existing errors (#1868)
- chore: move some logic into internal files (#1871)
- refactor: extract event-emitter to specific file (#1872)
- refactor!: make all methods take an object of params (#1873)
> latest of next to main

- .github/workflows/publish-package.yml
- .swiftlint.yml
- IapExample/ios/Podfile
- IapExample/ios/Podfile.lock
- RNIap.podspec
- docs/docs/usage_instructions/receipt_validation.md
- ios/IapSerializationUtils.swift
- ios/IapTypes.swift
- ios/IapUtils.swift
- ios/RNIapIos.m
- ios/RNIapIos.swift
- src/iap.ts
- src/types/index.ts
- set min ios version to 15
- consolidated buy methods
- removed checks for older versions of ios
- cleared most errors
- swiftlint
- continue migration, purchases
- return promises to class
- moved utils to ios
- clean up promises and error codes
- serialized Transactions
- removed remaining old methods, added serialization
- default to Xcode 4 spaces
- Split files
- Added more transaction methods
- removed global autofinish
- fix lint on doc
> integrate ios storekit 2

- IapExample/ios/Configuration.storekit
- IapExample/ios/IapExample.xcodeproj/project.pbxproj
- IapExample/ios/IapExample.xcodeproj/xcshareddata/xcschemes/IapExample.xcscheme
- IapExample/ios/Podfile.lock
- IapExample/src/screens/ClassSetup.tsx
- IapExample/src/screens/Products.tsx
- IapExample/src/screens/Subscriptions.tsx
- ios/IapSerializationUtils.swift
- ios/RNIapIos.m
- ios/RNIapIos.swift
- src/eventEmitter.ts
- src/hooks/useIAP.ts
- src/hooks/withIAPContext.tsx
- src/iap.ts
- src/types/index.ts
- Able to purchase products
- swift lint
- fixed lint issues, removed methods
> product purchase lifecycle

- docs/docs/usage_instructions/retrieve_available.md
In the source code, we have an object with one attribute: `skus`
```
export declare const getProducts: ({ skus, }: {
skus: string[];
}) => Promise<Array<Product>>;
```
> docs: Fixed getProducts signature

- android/src/amazon/java/com/dooboolab/RNIap/RNIapAmazonListener.kt
- android/src/amazon/java/com/dooboolab/RNIap/RNIapAmazonModule.kt
- android/src/main/java/com/dooboolab/RNIap/DoobooUtils.kt
- android/src/main/java/com/dooboolab/RNIap/PromiseUtlis.kt
- android/src/play/java/com/dooboolab/RNIap/RNIapModule.kt
- ios/RNIapIos.swift
When opening and closing connections, some pieces of data (particularly promises) were being kept possibly causing memory leaks and duplicate calls
> Clean up on disconnect

- src/iap.ts
The return was invalid.
Promise rejected was called without being returned, thus it didn't trigger the catch and it was handled inside finally statement.
> Fix subscriptionOffers promise rejected

- src/eventEmitter.ts
Fix for https://github.com/dooboolab/react-native-iap/issues/1930
This PR reverts it to the way it was handled on 9.x.x. Only create the emitter inside the listener
> create event emitter only when needed

- src/types/index.ts
- added the `offerTags` property to the `SubscriptionAndroid`
- There is no the `offerTags` property in the `SubscriptionAndroid` interface, so a lint error occurs when using the `offerTags`. So I added the `offerTags` property like this, but if it's unnecessary, you can reject it.
> fix: added the offerTags property to the SubscriptionAndroid

- docs/docs/migrate_to_11.0.0.md
`setup` seems to be a named export so it must be imported in curlies (`{setup}`)
> chore: use named export in docs for 11.0.0 migration

- src/types/index.ts
marks localizedPrice as optional and adds documentation on where to find the value for Android
> make it optional and add doc on wher to find it

- .eslintignore
- jest.config.js
- package.json
- src/__tests__/iap.test.ts
- tsconfig.json
While trying to work on this repository, I realized that the linting and tests were broken. To help ensure the tests and linting isn't broken by any new changes, I think it'd be great to run the linter and tests as part of the `prepare` release process.
1. Change `yarn prepare` to also run `yarn lint && yarn test`
- Create a separate `yarn build` command so we can build while skipping the lint/test process
2. Fix the test by moving the mock to the outermost scope
3. Fix the linting by adding excludes to the typechecker
Ran `yarn prepare` and verified that it runs successfully.
> Lint and run tests as part of yarn prepare to improve safety

- IapExample/src/screens/Subscriptions.tsx
- package.json
- src/__tests__/iap.test.ts
- src/iap.ts
- src/internal/fillProductsWithAdditionalData.ts
- src/internal/platform.ts
- src/modules/android.ts
- src/modules/ios.ts
- src/types/appleSk2.ts
- src/types/index.ts
- tsconfig.json
When I updated `react-native-iap` to 12.0.3 in my project, I realized that `getSubscriptions` on Android no longer returns anything resembling what the typings say they do.
Instead, I got back output that was very different on iOS and Android.
```ts
const subscription = {
subscriptionOfferDetails: [
{
pricingPhases: {
pricingPhaseList: [
{
recurrenceMode: 1,
priceAmountMicros: '49990000',
billingCycleCount: 0,
billingPeriod: 'P1Y',
priceCurrencyCode: 'USD',
formattedPrice: '$49.99',
},
],
},
offerTags: [],
offerToken: 'dGVzdA==',
},
],
name: 'MyApp Pro: Annual Plan',
productType: 'subs',
description: '',
title: 'MyApp Pro: Annual Plan (MyApp - Productivity App)',
productId: 'app_4999_1y_1w0',
};
```
1. Update the Typescript `Subscription` typings to use Union types
2. Since the …
> Fix getSubscriptions Android types; add platform enum and tests

- src/iap.ts
- src/modules/android.ts
I realized I accidentally removed the default value for `prorationModeAndroid`. This introduces the same crash that's mentioned in #1913
Fixes #1913
Restore the default `prorationMode` of -1
I introduced this bug because I didn't test thoroughly enough. I did a new round of testing to make sure it works end-to-end.
> Fix missing prorationModeAndroid causing crash

- ios/RNIapIosSk2.m
- ios/RNIapIosSk2.swift
- src/modules/iosSk2.ts
This PR adds support for showManageSubscriptions: https://developer.apple.com/documentation/storekit/appstore/3803198-showmanagesubscriptions
- This panel is very useful for testing where one can cancel the subscription and avoid waiting for expire and additional renewals.
- This panel is very user friendly allowing users to cancel or change their subscription without going to the App Store or Settings app to find their subscription.
> Added support for showManageSubscriptions on Storekit 2

- ios/RNIapIosSk2.m
- ios/RNIapIosSk2.swift
- package.json
- src/iap.ts
- src/modules/iosSk2.ts
Adds the `onlyIncludeActiveItems` parameter to `getAvailablePurchases` (defaults to true) and `getPurchaseHistory` (defaults to false). It allows to skip the validation of the item being active that caused empty array being returned in `getPurchaseHistory` 
- Implementation of onlyIncludeActiveItems
- lint fix
> onlyIncludeActiveItems ios sk2

- src/iap.ts
The iOS Native purchase doesn't return anything when finishing transactions. I'm changing the code to always return true for iOS. Note that Android does return the purchase result. I added a quick note in the documentation
> finish transaction returns true on iOS

- src/iap.ts
Filtering makes it impossible to get non-renewable subscriptions: https://github.com/dooboolab/react-native-iap/issues/2176
> Fix empty subscriptions list by removing filter

- IapExample/android/build.gradle
- android/src/amazon/java/com/dooboolab/RNIap/EventSender.kt
- android/src/amazon/java/com/dooboolab/RNIap/RNIapAmazonListener.kt
- android/src/amazon/java/com/dooboolab/RNIap/RNIapAmazonModule.kt
- android/src/testAmazon/java/com/dooboolab/RNIap/RNIapAmazonModuleTest.kt
This will make it easier to write unit tests and it's a better practice since the listener doesn't need to know how messages are sent
> Decouple reactContext from AmazonListener

- IapExample/android/app/src/main/java/com/iapexample/MainActivity.java
- android/src/amazon/java/com/dooboolab/RNIap/RNIapActivityListener.kt
- android/src/amazon/java/com/dooboolab/RNIap/RNIapAmazonListener.kt
- android/src/amazon/java/com/dooboolab/RNIap/RNIapAmazonModule.kt
- android/src/play/java/com/dooboolab/RNIap/RNIapActivityListener.kt
- android/src/testAmazon/java/com/dooboolab/RNIap/RNIapAmazonModuleTest.kt
- docs/docs/guides/amazon-iap.md
The amazon IAP purchase listener needs to be registered on Activity.onCreate, otherwise, instead of the native purchase dialog you get an infinite spinner. This PR fixes it by adding the means to register the listener from `MainActivity`
> Fixed infinite spinner on Amazon IAP

- .gitignore
- .npmignore
- app.plugin.js
- docs/docs/faq.md
- jest.config.js
- package.json
- plugin/__tests__/fixtures/buildGradleFiles.ts
- plugin/__tests__/withIAP-test.ts
- plugin/build/withIAP.d.ts
- plugin/build/withIAP.js
- plugin/jest.config.js
- plugin/src/withIAP.ts
- plugin/tsconfig.json
- yarn.lock
Currently, you cannot use `react-native-iap` with expo (at least on android), because you have to configure `build.gradle`. Building an android app results in the following error:
```
* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
> Could not resolve project :react-native-iap.
Required by:
project :app
> The consumer was configured to find an API of a component, preferably optimized for Android, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'com.android.build.api.attributes.AgpVersionAttr' with value '7.2.1'. However we cannot choose between the following variants of project :react-native-iap:
- …
```
> feat: add expo config plugin

- package.json
Currently, the `plugin/build` and `app.plugin.js` directories are missing from the package installed via npm. I forgot to add them to the `files` array in package.json 🤦‍♂️
> fix: include expo plugin in package.json files

- android/src/play/java/com/dooboolab/RNIap/RNIapModule.kt
- android/src/testPlay/java/com/dooboolab/RNIap/RNIapModuleTest.kt
- src/__tests__/iap.test.ts
- src/types/index.ts
At the moment, "basePlanId" and "offerId" fields are missing in subscriptionOfferDetails. Those are very important fields when filtering the offers in complex subscription structures. 
See android docs: https://developer.android.com/reference/com/android/billingclient/api/ProductDetails.SubscriptionOfferDetails
PS:[ react-native-iap docs](https://react-native-iap.dooboolab.com/docs/api/interfaces/SubscriptionOfferAndroid) need to be updated after this change.
> [Android] subscriptionOfferDetails - added "basePlanId" & "offerId" fields

- ios/RNIapIosSk2.swift
This fix allows developers to know whether user has cancelled the purchase or not when using StoreKit2.
> fix: case of user cancelled case

- ios/RNIapIosSk2.swift
Starting transaction listener at constructor causes unfinished transactions to be missed. This improvement allows developers to start listening transactions right time (when JS Thread bootstraps and then IAP module initialized)
> Fix place of addTransactionObserver

- ios/RNIapIosSk2.swift
Xcode Main Thread Checker reported `UIApplication.shared.connectedScenes` is called on a background thread when use `showManageSubscriptions` API. We should call the UI API in the main thread.
Full log:
```
Main Thread Checker: UI API called on a background thread: -[UIApplication connectedScenes]
PID: 86915, TID: 487323, Thread name: (none), Queue name: com.facebook.react.RNIapIosSk2Queue, QoS: 0
Backtrace:
4   GcoresMobile                        0x0000000102873262 $s5RNIap0A11IosSk2iOS15C23showManageSubscriptions_6rejectyyypSgc_ySSSg_AGs5Error_pSgtctF + 210
5   GcoresMobile                        0x0000000102877338 $s5RNIap0A11IosSk2iOS15CAA11Sk2DelegateA2aDP23showManageSubscriptions_6rejectyyypSgc_ySSSg_AIs5Error_pSgtctFTW + 24
6   GcoresMobile                        0x00000001028606cd …
```
> fix(ios): fix `connectedScenes` is called in background thread

- ios/IapSerializationUtils.swift
- ios/RNIapIosSk2.swift
- src/types/appleSk2.ts
- src/types/index.ts
This PR adds the JWS representation of the App Store verification when using StoreKit 2 (iOS/tvOS) to the purchase response as well as `purchase-updated` and `iap-transaction-updated` events.
> feat: include JWS representation of purchase verification when using StoreKit 2

- docs/docs/guides/purchases.md
The example shown in purchases.md has the wrong interface use for the function `requestSubscription`
In the docs example is shown as
```typescript
await requestSubscription(
{sku},
...(offerToken && {subscriptionOffers: [{sku, offerToken}]}),
);
```
While the interface to the function requires an object of the type `RequestSubscription` and not 2 args
> docs: purchases.md use object instead of params in requestSubscription call

- src/iap.ts
This PR fixed TS definitions for requestPurchase and requestSubscription functions.
Ensured that the return values align with the expected types.
ref: https://github.com/dooboolab-community/react-native-iap/issues/2426
> fix: update TS definitions for purchase methods (#2509)

- android/gradle.properties
Recently, a warning in Google Play Console appears due to the Google Play Billing Version not being updated enough:
In order to support Android 14 while not introducing breaking changes in the library, I've updated the minor version of the SDK to `5.2.1`
Further reading:
https://android-developers.googleblog.com/2023/06/changes-to-google-play-developer-api-june-2023.html
https://developer.android.google.cn/google/play/billing/release-notes#5-2-1
> Enable support for Android 14

- src/types/appleSk2.ts
- src/types/index.ts
> fix: added missing iOS appAccountToken on ProductPurchase TS interface

- docs/docs/get-started.md
#2535
After version `12.10.7` build will fail with
```
INF/java.com.google.android.libraries.play.billing.public.ktbilling_granule.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
```
Downgrading to `12.10.5` works with 1.6.0
> Update Kotlin Version In Docs  

- ios/RNIapIosSk2.swift
Doing `getProduct` on iOS would sometimes cause a crash due to a racing condition. This fixes it.
Basically this change makes the products' store and listeners thread-safe.
> fix: race condition crash

- docs/docs/get-started.mdx
While integrating this on Android, I found that the suggested gradle import changes weren't correct on the [Get Started page](https://react-native-iap.dooboolab.com/docs/get-started#with-androidx).
I have made the correction in this PR.
> fix: correct gradle import instructions in get-started.mdx

- .github/workflows/ci-example-android.yml
- android/gradle.properties
- android/src/amazon/java/com/dooboolab/rniap/RNIapAmazonListener.kt
- android/src/main/java/com/dooboolab/rniap/PromiseUtils.kt
It's just one patch upgrade, as you can see in the [release notes](https://developer.amazon.com/docs/appstore-sdk/release-notes.html) nothing breaking was introduced so the upgrade will be smooth.
> Upgrade Amazon's SDK to 3.0.4

- CONTRIBUTING.md
- IapExample/README.md
- IapExample/package.json
- IapExample/yarn.lock
- improve setup of project
- remove not working scripts and urls
- I managed to get Android example app to work, but unfortunately not the iOS, see notes bellow:
- because of  `TypeError: undefined is not an object (evaluating 'ReactCurrentActQueue$1.isBatchingLegacy')`
- see here: https://github.com/facebook/react-native/issues/34079
- because of obsolete pods:
```
$ yarn pods
rbenv: pod: command not found
The `pod' command exists in these Ruby versions:
2.7.4
```
- see here: https://github.com/facebook/react-native/issues/38921
fixed but then build failed
```
The following build commands failed:
CompileC /Users/babu/Library/Developer/Xcode/DerivedData/IapExample-ddzasbbwninhdjgvtldlfwsnfkwf/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RCT-Folly.build/Objects-normal/arm64/ …
```
> docs: improve documentation 17.11.2023

- ios/IapSerializationUtils.swift
- ios/RNIapIosSk2.swift
- src/types/appleSk2.ts
- src/types/index.ts
- add renewal info (uncomment and serialize)
- change debugSerialize to serialize - there is info in this property useful for production not only for development
- added transactionReasonIOS enum (to distinguish between type of renewing transactions of purchase events)
see also: [JWSTransactionDecodedPayload](https://developer.apple.com/documentation/appstoreserverapi/jwstransactiondecodedpayload)
> feat: add renewal info for Storekit 2

- ios/IapSerializationUtils.swift
- ios/RNIapIosSk2.swift
- src/types/appleSk2.ts
- addressing the missing currency issue in Storekit 2: https://developer.apple.com/forums/thread/689978
- adding from here: https://developer.apple.com/documentation/storekit/product/4044347-priceformatstyle
- as few changes as possible
> feat: add currency regarding the new API

- src/types/appleSk2.ts
Adding missing mapping for intro offers in storekit2 on existing type
> fix: add missing conn for SK2 intro offers

- ios/RNIapIosSk2.swift
- src/modules/iosSk2.ts
Added a previously missing exported function that allows manual completion of transactions in **StoreKit2**.
Function has already been described in the interface of the **IosModulePropsSk2** in the codebase but lacked accessible invocation.
The function is crucial and must be used to manually complete transactions in in-app purchases using **StoreKit2**.
> feat: Added export finishTransaction() from StoreKit2.

- ios/RNIapIosSk2.swift
Probably, someone forgot to delete the old **Reject** when adding the condition to the code. This leads to an error and crash of the application in the development environment. 
**Steps To Reproduce**:
The error occurs when the user has canceled iOS system prompt for Sync with App Store using StoreKit2.
**Error Message:**
The error says: 'Illegal callback invocation from native module. This callback type only permits a single invocation from native code.'
**Solution**:
Delete redundant reject.
> fix: avoid app crash due to multiple reject invocation

- docs/docs/api-reference/hooks.md
The documentation of getProducts hook was outdated.
If you agree, I'd also add more comprehensive documentation when it comes to handling errors. I was getting an empty products list and without adding the `.catch` statement to the `getProducts` and seeing that I was missing the `skus` property, I couldn't figure it out. I think it should be clear from the documentation that `getProducts` returns a promise.
> Update hooks.md documentation

- IapExample/ios/Podfile.lock
- IapExample/yarn.lock
- package.json
- yarn.lock
`@expo/config-plugins` at version 6.0.1 contains the deep dependency `xml2js` at version 0.4.23.
This package contains a vulnerability as described here: https://security.snyk.io/vuln/SNYK-JS-XML2JS-5414874.
This PR updates `@expo/config-plugins` to version 7.8.4 which is the latest version and contains the `xml2js` at version 0.6.0. As defined in the link above, as this version is greater than 0.5.0, it has the vulnerability fixed.
- Updated the `package.json` and `yarn`.
- Smoke tested the app in iOS
- Ran the tests and linting, all seems to be passing
> chore: Update Expo Config Plugins

- docs/docs/get-started.mdx
After the ipa package generated by Xcode archive  was installed on on iPhone 6 / iOS 12. It crashed every time I opened the app.
More information can be found here [#2701](https://github.com/dooboolab-community/react-native-iap/issues/2701)
Add a note in get-started.mdx. So developers know to do extra configuration on iOS 12 to avoid crashes
> Update get-started.mdx to avoid crashing when app launching on iOS 12 

- .github/workflows/ci-example-ios.yml
- ios/RNIapIosSk2.swift
During some testing of restoring purchases using the getAvailablePurchases method with the alsoPublishToEventListener argument set to true I noticed that the events were not being published correctly. I also noticed in the logs an error message saying that purchase-update was not a supported event.
I had a look at the code in RNIapIosSk2.swift and it appears that the event name should actually be purchase-updated.
I fixed this locally and the error no longer appears and the purchase is now being published to the event listener.
Creating this as a draft PR as I am not too sure if there is anything else I need to do, this is my first contribution to the project.
> fix: Send purchase-updated instead of purchase-update.

- src/hooks/useIAP.ts
This PR sets currentPurchaseError to undefined when useIAP hook gets unmount. 
It's very important because when user first time goes to subscription screen and there is a useIAP hook and user try to purchase and fail then we get error. But user when again come backs to this screen then that currentPurchaseError value must be undefined but it's not undefined so this is a problem and I address this thing in this PR.
For Example: (Steps)
- "A" Screen has useIAP hook
- User comes to "A" Screen
- Try to purchase and Gets error
- Then user goes back and Come again to this screen
- Then user sees error because currentPurchaseError has still some value (So, we need to get this undefined each time when useIAP get unmount)
Conclusion: It makes sense that currentPurchaseError should be undefined on …
> fix: setting currentPurchaseError to undefined on useIAP hook unmount

- package.json
- yarn.lock
Updated the version of `@expo/config-plugins` from `^7.8.4` to `^8.0.4` to add support for Expo SDK 51.
- Tested the change in my production app.
- Verified that the app works as expected with the updated plugin version and Expo SDK 51.
N/A
> chore: update expo config plugin for SDK 51

- .github/workflows/ci-example-ios.yml
- RNIap.podspec
- ios/IapSerializationUtils.swift
- ios/IapUtils.swift
- ios/RNIapIosSk2.m
- ios/RNIapIosSk2.swift
This PR adds visionOS support. 
I've refactored some parts of the code to take the currently presented scene by wrapping built-in utility `RCTKeyWindow()` to work in async scenarios.  
1. `npx @callstack/react-native-visionos init App`
2. Add react-native-iap
3. Check out if it works
https://github.com/dooboolab-community/react-native-iap/assets/52801365/c2391f3a-c8b9-4fd8-acba-e2871c7aaae7
> feat: add visionOS support

- CONTRIBUTING.md
- IapExample/README.md
- IapExample/ios/Podfile.lock
- IapExample/yarn.lock
- README.md
- docs/docs/api-reference/hooks.md
- docs/src/pages/index.js
- docs/src/uis/AdFit.js
- docs/src/uis/AdFitTopFixed.js
- package.json
- plugin/__tests__/withIAP-test.ts
- plugin/build/withIAP.d.ts
- plugin/build/withIAP.js
- plugin/src/withIAP.ts
- src/eventEmitter.ts
- src/modules/iosSk2.ts
- yarn.lock
> chore: migrate expo config plugins

- android/gradle.properties
- android/src/amazon/java/com/dooboolab/rniap/PurchasingServiceProxy.kt
- android/src/amazon/java/com/dooboolab/rniap/PurchasingServiceProxyAmazonImpl.kt
- android/src/amazon/java/com/dooboolab/rniap/RNIapAmazonListener.kt
- android/src/amazon/java/com/dooboolab/rniap/RNIapAmazonModule.kt
- android/src/amazon/java/com/dooboolab/rniap/RNIapPackage.kt
- android/src/main/java/com/dooboolab/rniap/PromiseUtils.kt
- android/src/main/java/com/dooboolab/rniap/PromiseUtlis.kt
- android/src/play/java/com/dooboolab/rniap/PlayUtils.kt
- android/src/play/java/com/dooboolab/rniap/RNIapModule.kt
- android/src/play/java/com/dooboolab/rniap/RNIapPackage.kt
- android/src/testAmazon/java/com/dooboolab/rniap/RNIapAmazonModuleTest.kt
- android/src/testPlay/java/com/dooboolab/rniap/RNIapModuleTest.kt
- package.json
- plugin/build/withIAP.d.ts
- plugin/build/withIAP.js
https://developer.android.com/google/play/billing/migrate-gpblv7
Related: #2755
> migration(android): billingClient 7.0.0

- ios/LatestPromiseKeeper.swift
- Closes #2776 
- Fixes iOS bug on StoreKit 1 mode where making more than one request for products or subscriptions resulted in a crash
- Now properly clears request and promise references on promise resolution, rejection or cancel
https://github.com/dooboolab-community/react-native-iap/assets/3487334/fe610d66-e6e9-4489-9068-0169e1902c88
https://github.com/dooboolab-community/react-native-iap/assets/3487334/8e52287e-54b1-4cb5-b1c4-b807aceb686e
> fix: latest promise crash on StoreKit 1

- src/iap.ts
- src/modules/android.ts
- src/types/index.ts
Fixed missing changes in https://github.com/dooboolab-community/react-native-iap/pull/2764
> fix: migrate ProrationMode to ReplacementMode

- src/iap.ts
`useCallback` returns a function (async in this case) that cannot be directly used in the render phase.
Therefore, a state should hold the result of the fetch.
> doc(requestPurchase): fix the example in docstrings

- src/hooks/useIAP.ts
- src/hooks/withIAPContext.tsx
- src/iap.ts
Hello.
I faced one problem using this.
Though a first purchase after the in-app connection is successful, the store purchase will be completed, but the `currentPurchase` status is not updating inside the library. I would have to repeat the purchase process by killing the app. 
In my opinion, the purchaseListener is connected by the change of the `connected` value inside `useEffect`, which changes from `false` to `true` only when the app is first connected and not after that, so I decided that I can't subscribe to the status of the current order.
So I added a code inside the `endConnection` method to make `connected` false.
This allows you to update every subscription correctly by changing `connected` to `true` when you access the order page and `false` when you access `endConnection`. …
> fix: set connected false in endConnection

- docs/docs/get-started.mdx
After much head-scratching I found the plugin and config options for Expo in the [react-native-iap FAQs section](https://react-native-iap.dooboolab.com/docs/faq#how-do-i-use-react-native-iap-in-expo).
I expected to see it on the ["Get Started" docs page](https://react-native-iap.dooboolab.com/docs/get-started). This PR adds Expo instructions to the Get Started docs page.
> Add instructions for using as an Expo package to get-started.mdx.

- ios/RNIapIosSk2.swift
fix #2830
As stated in the issue, an error occurs when attempting to build with Swift versions below 5.9, so this is being fixed."
> Add conditional macro to omit confirmIn argument for Swift versions below 5.9

- docs/docs/guides/purchases.mdx
Replaced the link for "Integrate the Google Play Billing Library" from the Chines  version to the English version
> Update link in purchases.mdx

- android/build.gradle
- android/gradle.properties
- android/src/amazon/java/com/dooboolab/rniap/RNIapAmazonModule.kt
- docs/docs/guides/amazon-iap.mdx
- plugin/__tests__/fixtures/buildGradleFiles.ts
In some cases, users want to manage the DRM with their own solution and not use Amazon's DRM. In the past, this was possible by unchecking the DRM option from Amazon's Developer console, but now you can only do it from their SDK.
The `react-native-iap` module by default will enable Amazon's DRM, but if a user doesn't want to leverage it, there is no option to disable it.
With this PR a user can easily disable it by adding `isAmazonDrmEnabled=false` to their **gradle.properties** file.
The default will be `true`
> Ability to disable amazon's DRM

- android/src/main/java/com/dooboolab/rniap/PromiseUtlis.kt
When using React Native 0.76 the Android build fails with an error:
```
java/com/dooboolab/RNIap/PromiseUtlis.kt:40:21 Type mismatch: inferred type is String? but String was expected
```
The issue seems to be caused by the fact that in RN 0.76 the Promise class was rewritten from Java to Kotlin and the code parameter of the reject method is a non-nullable String now: https://github.com/facebook/react-native/commit/de73e44569fd2932fe5683f7a392f37d866e5d35#diff-74cbd5a9d82e4c21dbc37dd72a92e31542e574dc6425d2454c3ce53e71e08bbeR31 but in react-native-iap it is called with a nullable string: https://github.com/hyochan/react-native-iap/blob/12.15.6/android/src/main/java/com/dooboolab/rniap/PromiseUtlis.kt#L40.
This change updates that call to use an empty string "" for code if for some reason …
> fix: android build error with React Native 0.76

- ios/RNIapIosSk2.swift
As mentioned here: https://github.com/hyochan/react-native-iap/issues/2533 `verificationResultIOS` is not present when we call `getAvailablePurchases`. Therefore we are not able to verify the transaction from the server side.
We just need to send the verification object to the already implemented serializer.
> fix: storekit2 add verificationResultIOS to getAvailablePurchases

- android/src/main/java/com/dooboolab/rniap/PromiseUtils.kt
- android/src/main/java/com/dooboolab/rniap/PromiseUtlis.kt
The reject method of Promise class became non-nullable in React Native 0.76 after rewriting it from Java to Kotlin. We fixed it being called with a nullable value in https://github.com/hyochan/react-native-iap/pull/2872 by providing and empty string as a fallback if it happens to be null. But after more investigation it seems like it's not called with a value that could be null anywhere in the code, so a better solution would be to just update the type of the `code` parameter to be non-nullable.
> refactor: make the code parameter of safeReject non-nullable

- android/src/amazon/java/com/dooboolab/rniap/RNIapAmazonModule.kt
- android/src/play/java/com/dooboolab/rniap/RNIapModule.kt
**Summary:**
While working on my fork I noticed a few places which could be a bit polished in Kt code. Reduces nesting, removes unnecessary checks and other minor styling.
**Test plan:**
- Doesn't change the flow in any way so simply smoke testing the Example app.
> refactor: minor Kt code cleanup

- RNIap.podspec
This dependency is not needed (empty dependency) and is affecting building tvos projects using react-native-iap:
```
[!] The platform of the target `project-tvOS` (tvOS 15.1) is not compatible with `React-Codegen (0.1.0)`, which does not support `tvOS`.
```
> Remove useless React-Codegen pod dependency

- android/src/play/java/com/dooboolab/rniap/RNIapModule.kt
- ios/RNIapIosSk2.m
- ios/RNIapIosSk2.swift
- src/iap.ts
- src/modules/android.ts
- src/modules/iosSk2.ts
Hello, I've been using this method in my fork for a while. And i think it would be very usefull to have this in main repo.
> feat: getStorefront method implementation for fetching App Store and Google Play region

- android/src/amazon/java/com/dooboolab/rniap/RNIapAmazonModule.kt
- android/src/main/java/com/dooboolab/rniap/PromiseUtlis.kt
- android/src/play/java/com/dooboolab/rniap/RNIapModule.kt
Fixed type mismatch errors in RNIapModule.kt by properly handling nullable strings using orEmpty()
> fix: handle nullable strings in react-native-iap kotlin code

- docs/docs/guides/purchases.mdx
- `finishTransaction` import was missing from the code snippet
> fix: add missing import in example

- .github/workflows/ci-example-android.yml
- IapExample/android/gradle/wrapper/gradle-wrapper.properties
- IapExample/babel.config.js
- IapExample/ios/IapExample.xcodeproj/project.pbxproj
- IapExample/ios/IapExample/PrivacyInfo.xcprivacy
- IapExample/ios/Podfile.lock
- IapExample/package.json
- IapExample/yarn.lock
- babel.config.js
- package.json
**Description:** 
bump RN to 0.72.17 to fix boost error in pod update for IapExample app
Fix all CI builds
> Installing boost (1.76.0)
> 
> [!] Error installing boost
> Verification checksum was incorrect, expected f0397ba6e982c4450f27bf32a2a83292aba035b827a5623a14636ea583318c41, got 79e6d3f9[86](https://github.com/hyochan/react-native-iap/actions/runs/14511508084/job/40711080218?pr=2943#step:12:87)444e5a80afbeccdaf2d1c1cf964baa8d766d20859d653a16c39848
**Test plan:**
Confirm the the test IapExample app can be built and run in usual way.
> chore: bump RN to 0.72.17

- README.md
Fix typo: correct "maintenenance" to "maintenance" in README.md
Corrected a spelling error in the Version 8.0.0 section of the README.md file.
> Fix typo: correct "maintenenance" to "maintenance" in README.md

- ios/IapSerializationUtils.swift
- ios/RNIapIosSk2.m
- ios/RNIapIosSk2.swift
- src/iap.ts
- src/modules/iosSk2.ts
- src/types/appleSk2.ts
- src/types/index.ts
This PR adds proper support for `appTransactionID` through the AppTransaction API and fixes the compilation error reported in #2967.
- PR #2950 incorrectly added `appTransactionID` to the `Transaction` type
- `appTransactionID` is actually a property of `AppTransaction`, not `Transaction`
- This caused compilation errors as reported in issue #2967
- Removed `appTransactionID` from `Transaction` type (fixing the compilation error)
- Added new `getAppTransaction()` method to properly access `AppTransaction` data
- Implemented proper Swift bridge for iOS 16.0+ AppTransaction API
- Added `getAppTransaction` method in `RNIapIosSk2.swift` with iOS 16.0+ availability check
- Added bridge method in `RNIapIosSk2.m`
- Fixed `IapSerializationUtils.swift` by removing incorrect `appTransactionID` …
> feat(ios): add AppTransaction support with appTransactionID
